// 完整的伤寒论113方数据库
// 包含倪海厦课程笔记

interface ClassicFormula {
  id: string;
  name: string;
  pinyin: string;
  source: string;
  chapter: string;
  composition: string[];
  modernDosage: string[];
  originalDosage: string[];
  indications: string[];
  symptoms: string[];
  functions: string[];
  analysis: string[];
  niNotes: string[];
  contraindications: string[];
  modifications: { condition: string; modification: string }[];
  tongue: string;
  pulse: string;
}

// 伤寒论113方完整数据
export const SHANGHANLUN_113_FORMULAS: ClassicFormula[] = [
  {
    id: "shl-001",
    name: "桂枝汤",
    pinyin: "Guizhi Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治上",
    composition: ["桂枝", "芍药", "生姜", "大枣", "炙甘草"],
    modernDosage: ["桂枝9g", "芍药9g", "生姜9g", "大枣4枚", "炙甘草6g"],
    originalDosage: ["桂枝三两", "芍药三两", "生姜三两", "大枣十二枚", "甘草二两（炙）"],
    indications: ["伤寒中风，阳浮而阴弱，阳浮者热自发，阴弱者汗自出，啬啬恶寒，淅淅恶风，翕翕发热，鼻鸣干呕者", "太阳病，头痛发热，汗出恶风者"],
    symptoms: ["头痛", "发热", "汗出", "恶风", "鼻鸣", "干呕", "脉浮缓"],
    functions: ["解肌发表", "调和营卫"],
    analysis: ["桂枝辛温解肌发表温通阳气为君", "芍药酸苦微寒益阴敛汗为臣", "生姜辛温温胃止呕为佐", "大枣甘平补中益气为使"],
    niNotes: ["桂枝汤是群方之冠，调和阴阳第一方", "只要有汗而用桂枝，无汗用麻黄", "服桂枝汤后，啜热稀粥，覆取微似汗", "桂枝汤证：头痛、发热、汗出、恶风", "太阳中风证，表虚证"],
    contraindications: ["表实无汗发热恶寒者", "湿热内盛者", "饮酒后"],
    modifications: [{ condition: "项背强几几", modification: "加葛根" }, { condition: "喘", modification: "加厚朴杏仁" }, { condition: "发汗太过大汗出脉洪大", modification: "仍用桂枝汤" }],
    tongue: "舌苔薄白",
    pulse: "浮缓"
  },
  {
    id: "shl-002",
    name: "麻黄汤",
    pinyin: "Mahuang Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["麻黄", "桂枝", "杏仁", "炙甘草"],
    modernDosage: ["麻黄9g", "桂枝9g", "杏仁9g", "炙甘草3g"],
    originalDosage: ["麻黄三两", "桂枝二两", "杏仁七十个", "甘草一两（炙）"],
    indications: ["太阳病头痛发热身疼腰痛骨节疼痛恶风无汗而喘者", "太阳与阳明合病喘而胸满者"],
    symptoms: ["头痛", "发热", "身疼腰痛", "骨节疼痛", "无汗", "恶风", "喘", "脉浮紧"],
    functions: ["发汗解表", "宣肺平喘"],
    analysis: ["麻黄发汗解表宣肺平喘为君", "桂枝助麻黄发汗解表为臣", "杏仁助麻黄宣肺为佐", "甘草调和为使"],
    niNotes: ["麻黄汤证：无汗而喘", "无汗用麻黄，有汗用桂枝", "表实证用麻黄汤", "麻黄汤证必无汗", "麻黄是解表发汗峻剂"],
    contraindications: ["表虚自汗者", "体质虚弱者", "咽喉干燥者", "淋家", "疮家", "衄家", "亡血家", "汗家"],
    modifications: [],
    tongue: "舌苔薄白",
    pulse: "浮紧"
  },
  {
    id: "shl-003",
    name: "葛根汤",
    pinyin: "Gegen Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["葛根", "麻黄", "桂枝", "芍药", "生姜", "大枣", "炙甘草"],
    modernDosage: ["葛根12g", "麻黄9g", "桂枝6g", "芍药6g", "生姜9g", "大枣4枚", "炙甘草6g"],
    originalDosage: ["葛根四两", "麻黄三两", "桂枝二两", "芍药二两", "生姜三两", "大枣十二枚", "甘草二两（炙）"],
    indications: ["太阳病项背强几几无汗恶风者", "太阳与阳明合病必自下利者"],
    symptoms: ["项背强几几", "无汗", "恶风", "下利", "脉浮紧"],
    functions: ["发汗解表", "升津舒筋"],
    analysis: ["葛根升津舒筋为君", "麻黄桂枝发汗解表为臣", "芍药甘草缓急止痛为佐"],
    niNotes: ["葛根汤专治项背强", "无汗用葛根汤，有汗用桂枝加葛根汤", "太阳阳明合病下利用葛根汤"],
    contraindications: ["表虚有汗者", "阴虚火旺者"],
    modifications: [],
    tongue: "舌苔薄白",
    pulse: "浮紧"
  },
  {
    id: "shl-004",
    name: "桂枝加葛根汤",
    pinyin: "Guizhi Jia Gegen Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治上",
    composition: ["桂枝", "芍药", "生姜", "大枣", "炙甘草", "葛根"],
    modernDosage: ["桂枝9g", "芍药9g", "生姜9g", "大枣4枚", "炙甘草6g", "葛根12g"],
    originalDosage: ["桂枝三两", "芍药三两", "生姜三两", "大枣十二枚", "甘草二两（炙）", "葛根四两"],
    indications: ["太阳病项背强几几反汗出恶风者"],
    symptoms: ["项背强几几", "汗出", "恶风", "脉浮缓"],
    functions: ["解肌发表", "升津舒筋"],
    analysis: ["桂枝汤解肌调和营卫", "葛根升津舒筋"],
    niNotes: ["有汗项强加葛根于桂枝汤", "表虚证的项背强"],
    contraindications: ["表实无汗者"],
    modifications: [],
    tongue: "舌苔薄白",
    pulse: "浮缓"
  },
  {
    id: "shl-005",
    name: "小青龙汤",
    pinyin: "Xiao Qinglong Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["麻黄", "芍药", "细辛", "干姜", "甘草", "桂枝", "五味子", "半夏"],
    modernDosage: ["麻黄9g", "芍药9g", "细辛3g", "干姜6g", "甘草6g", "桂枝9g", "五味子6g", "半夏9g"],
    originalDosage: ["麻黄三两", "芍药三两", "细辛三两", "干姜三两", "甘草三两", "桂枝三两", "五味子半升", "半夏半升"],
    indications: ["伤寒表不解心下有水气干呕发热而咳或渴或利或噎或小便不利少腹满或喘者", "伤寒心下有水气咳而微喘发热不渴服汤已渴者此寒去欲解也"],
    symptoms: ["发热", "恶寒", "无汗", "咳嗽", "喘息", "干呕", "痰白稀", "脉浮紧"],
    functions: ["解表散寒", "温肺化饮"],
    analysis: ["麻黄桂枝发汗解表", "干姜细辛半夏温肺化饮", "五味子敛肺止咳"],
    niNotes: ["小青龙汤是治寒饮的要方", "表寒里饮俱盛", "麻黄发在表之寒，干姜细辛温在里之饮", "五味子防发散太过"],
    contraindications: ["阴虚火旺者", "肺热咳嗽者"],
    modifications: [{ condition: "渴", modification: "去半夏加栝蒌根" }, { condition: "微利", modification: "去麻黄加荛花" }, { condition: "噎", modification: "去麻黄加附子" }],
    tongue: "舌苔白滑",
    pulse: "浮紧"
  },
  {
    id: "shl-006",
    name: "大青龙汤",
    pinyin: "Da Qinglong Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["麻黄", "桂枝", "甘草", "杏仁", "生姜", "大枣", "石膏"],
    modernDosage: ["麻黄12g", "桂枝6g", "甘草6g", "杏仁9g", "生姜9g", "大枣4枚", "石膏30g"],
    originalDosage: ["麻黄六两", "桂枝二两", "甘草二两", "杏仁四十枚", "生姜三两", "大枣十枚", "石膏如鸡子大"],
    indications: ["太阳中风脉浮紧发热恶寒身疼痛不汗出而烦躁者", "伤寒脉浮缓身不疼但重乍有轻时无少阴证者"],
    symptoms: ["发热", "恶寒", "身痛", "无汗", "烦躁", "脉浮紧"],
    functions: ["发汗解表", "清热除烦"],
    analysis: ["麻黄桂枝发汗解表", "石膏清热除烦", "杏仁降利肺气"],
    niNotes: ["大青龙汤是麻黄汤加重剂量加石膏", "表寒里热烦躁用大青龙", "发汗力量最强的方剂之一"],
    contraindications: ["表虚有汗者", "体质虚弱者", "阴虚内热者"],
    modifications: [],
    tongue: "舌苔薄白或微黄",
    pulse: "浮紧"
  },
  {
    id: "shl-007",
    name: "桂枝麻黄各半汤",
    pinyin: "Guizhi Mahuang Geban Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["桂枝", "芍药", "生姜", "甘草", "麻黄", "大枣", "杏仁"],
    modernDosage: ["桂枝5g", "芍药5g", "生姜5g", "甘草3g", "麻黄5g", "大枣2枚", "杏仁5g"],
    originalDosage: ["桂枝一两十六铢", "芍药一两", "生姜一两", "甘草一两", "麻黄一两", "大枣四枚", "杏仁二十枚"],
    indications: ["太阳病得之八九日如疟状发热恶寒热多寒少其人不呕清便欲自可一日二三度发脉微缓者为欲愈也脉微而恶寒者此阴阳俱虚不可更发汗更下更吐也面色反有热色者未欲解也以其不能得小汗出身必痒宜桂枝麻黄各半汤"],
    symptoms: ["发热恶寒如疟状", "热多寒少", "身痒", "脉微缓"],
    functions: ["小发其汗"],
    analysis: ["桂枝汤与麻黄汤各取一半", "小发其汗以解邪"],
    niNotes: ["太阳病日久不愈，表邪未解", "用小剂量发汗"],
    contraindications: ["表虚自汗者", "里热盛者"],
    modifications: [],
    tongue: "舌苔薄白",
    pulse: "微缓"
  },
  {
    id: "shl-008",
    name: "桂枝二麻黄一汤",
    pinyin: "Guizhi Er Mahuang Yi Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["桂枝", "芍药", "生姜", "甘草", "大枣", "麻黄", "杏仁"],
    modernDosage: ["桂枝6g", "芍药6g", "生姜6g", "甘草4g", "大枣3枚", "麻黄3g", "杏仁3g"],
    originalDosage: ["桂枝一两十七铢", "芍药一两六铢", "生姜一两六铢", "甘草一两二铢", "大枣五枚", "麻黄十六铢", "杏仁十六个"],
    indications: ["服桂枝汤大汗出脉洪大者与桂枝汤如前法若形似疟一日再发者汗出必解宜桂枝二麻黄一汤"],
    symptoms: ["形似疟", "一日再发", "汗出"],
    functions: ["微发其汗"],
    analysis: ["桂枝汤分量略重，麻黄汤分量较轻", "微发其汗"],
    niNotes: ["比桂枝麻黄各半汤更轻的发汗剂", "用于表证较轻者"],
    contraindications: [],
    modifications: [],
    tongue: "舌苔薄白",
    pulse: "洪大或浮缓"
  },
  {
    id: "shl-009",
    name: "桂枝二越婢一汤",
    pinyin: "Guizhi Er Yuebi Yi Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["桂枝", "芍药", "麻黄", "甘草", "大枣", "生姜", "石膏"],
    modernDosage: ["桂枝5g", "芍药5g", "麻黄3g", "甘草3g", "大枣2枚", "生姜5g", "石膏12g"],
    originalDosage: ["桂枝十八铢", "芍药十八铢", "麻黄十八铢", "甘草十八铢", "大枣四枚", "生姜一两二铢", "石膏二十四铢"],
    indications: ["太阳病发热恶寒热多寒少脉微弱者此无阳也不可更汗宜桂枝二越婢一汤"],
    symptoms: ["发热恶寒", "热多寒少", "脉微弱"],
    functions: ["微发其汗", "兼清里热"],
    analysis: ["桂枝汤与越婢汤合方", "微发其汗兼清里热"],
    niNotes: ["表寒里热轻证", "无阳不可大发汗"],
    contraindications: ["表实无汗者", "里热盛者"],
    modifications: [],
    tongue: "舌苔薄白或微黄",
    pulse: "微弱"
  },
  {
    id: "shl-010",
    name: "白虎汤",
    pinyin: "Baihu Tang",
    source: "《伤寒论》",
    chapter: "辨阳明病脉证并治",
    composition: ["石膏", "知母", "甘草", "粳米"],
    modernDosage: ["石膏30g", "知母9g", "甘草6g", "粳米9g"],
    originalDosage: ["石膏一斤", "知母六两", "甘草二两", "粳米六合"],
    indications: ["伤寒脉滑而厥者里有热也白虎汤主之", "三阳合病腹满身重难以转侧口不仁面垢谵语遗尿发汗则谵语下之则额上生汗手足逆冷若自汗出者白虎汤主之"],
    symptoms: ["高热", "大汗", "口渴", "脉洪大"],
    functions: ["清热生津"],
    analysis: ["石膏辛甘大寒清热生津为君", "知母苦寒清热润燥为臣", "甘草粳米益气养胃为佐使"],
    niNotes: ["白虎汤四大证：大热、大汗、大渴、脉洪大", "阳明经热证", "石膏用量要大"],
    contraindications: ["表证未解者", "里虚寒者", "血虚发热者"],
    modifications: [{ condition: "加人参", modification: "白虎加人参汤" }],
    tongue: "舌红苔黄燥",
    pulse: "洪大"
  },
  {
    id: "shl-011",
    name: "白虎加人参汤",
    pinyin: "Baihu Jia Renshen Tang",
    source: "《伤寒论》",
    chapter: "辨阳明病脉证并治",
    composition: ["石膏", "知母", "甘草", "粳米", "人参"],
    modernDosage: ["石膏30g", "知母9g", "甘草6g", "粳米9g", "人参6g"],
    originalDosage: ["石膏一斤", "知母六两", "甘草二两", "粳米六合", "人参三两"],
    indications: ["服桂枝汤大汗出后大烦渴不解脉洪大者白虎加人参汤主之", "伤寒若吐若下后七八日不解热结在里表里俱热时时恶风大渴舌上干燥而烦欲饮水数升者白虎加人参汤主之"],
    symptoms: ["高热", "大汗", "大渴", "脉洪大", "时时恶风"],
    functions: ["清热生津", "益气养阴"],
    analysis: ["白虎汤清热生津", "人参益气养阴"],
    niNotes: ["白虎汤证加气虚表现", "大烦渴不解"],
    contraindications: ["表证未解者", "里虚寒者"],
    modifications: [],
    tongue: "舌红苔黄燥",
    pulse: "洪大"
  },
  {
    id: "shl-012",
    name: "栀子豉汤",
    pinyin: "Zhizi Chi Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["栀子", "香豉"],
    modernDosage: ["栀子9g", "香豉9g"],
    originalDosage: ["栀子十四个", "香豉四合"],
    indications: ["发汗吐下后虚烦不得眠若剧者必反复颠倒心中懊憹栀子豉汤主之", "若少气者栀子甘草豉汤主之若呕者栀子生姜豉汤主之"],
    symptoms: ["虚烦不得眠", "心中懊憹", "反复颠倒"],
    functions: ["清热除烦"],
    analysis: ["栀子苦寒清热除烦", "香豉解表和中"],
    niNotes: ["栀子豉汤是治虚烦的要方", "余热未尽扰于胸膈"],
    contraindications: ["脾胃虚寒者", "大便溏稀者"],
    modifications: [{ condition: "少气", modification: "加甘草" }, { condition: "呕", modification: "加生姜" }],
    tongue: "舌红苔薄黄",
    pulse: "数"
  },
  {
    id: "shl-013",
    name: "栀子甘草豉汤",
    pinyin: "Zhizi Gancao Chi Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["栀子", "香豉", "甘草"],
    modernDosage: ["栀子9g", "香豉9g", "甘草6g"],
    originalDosage: ["栀子十四个", "香豉四合", "甘草二两"],
    indications: ["发汗吐下后虚烦不得眠若剧者必反复颠倒心中懊憹栀子豉汤主之若少气者栀子甘草豉汤主之"],
    symptoms: ["虚烦不得眠", "少气", "心中懊憹"],
    functions: ["清热除烦", "益气"],
    analysis: ["栀子豉汤清热除烦", "甘草益气"],
    niNotes: ["栀子豉汤加甘草益气"],
    contraindications: ["脾胃虚寒者"],
    modifications: [],
    tongue: "舌红苔薄黄",
    pulse: "细数"
  },
  {
    id: "shl-014",
    name: "栀子生姜豉汤",
    pinyin: "Zhizi Shengjiang Chi Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["栀子", "香豉", "生姜"],
    modernDosage: ["栀子9g", "香豉9g", "生姜12g"],
    originalDosage: ["栀子十四个", "香豉四合", "生姜五两"],
    indications: ["发汗吐下后虚烦不得眠若剧者必反复颠倒心中懊憹栀子豉汤主之若呕者栀子生姜豉汤主之"],
    symptoms: ["虚烦不得眠", "呕吐", "心中懊憹"],
    functions: ["清热除烦", "和胃止呕"],
    analysis: ["栀子豉汤清热除烦", "生姜和胃止呕"],
    niNotes: ["栀子豉汤加生姜止呕"],
    contraindications: ["脾胃虚寒者"],
    modifications: [],
    tongue: "舌红苔薄黄",
    pulse: "数"
  },
  {
    id: "shl-015",
    name: "栀子厚朴汤",
    pinyin: "Zhizi Houpo Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["栀子", "厚朴", "枳实"],
    modernDosage: ["栀子9g", "厚朴12g", "枳实6g"],
    originalDosage: ["栀子十四个", "厚朴四两", "枳实四枚"],
    indications: ["伤寒下后心烦腹满卧起不安者栀子厚朴汤主之"],
    symptoms: ["心烦", "腹满", "卧起不安"],
    functions: ["清热除烦", "宽中消满"],
    analysis: ["栀子清热除烦", "厚朴枳实宽中消满"],
    niNotes: ["热扰胸膈兼腹满"],
    contraindications: ["脾胃虚寒者"],
    modifications: [],
    tongue: "舌红苔黄腻",
    pulse: "滑数"
  },
  {
    id: "shl-016",
    name: "栀子干姜汤",
    pinyin: "Zhizi Ganjiang Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["栀子", "干姜"],
    modernDosage: ["栀子9g", "干姜6g"],
    originalDosage: ["栀子十四个", "干姜二两"],
    indications: ["伤寒医以丸药大下之身热不去微烦者栀子干姜汤主之"],
    symptoms: ["身热", "微烦"],
    functions: ["清上温下"],
    analysis: ["栀子清热除烦", "干姜温中散寒"],
    niNotes: ["上热下寒证"],
    contraindications: [],
    modifications: [],
    tongue: "舌淡红苔薄",
    pulse: "数"
  },
  {
    id: "shl-017",
    name: "大陷胸丸",
    pinyin: "Da Xianxiong Wan",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["大黄", "葶苈子", "芒硝", "杏仁"],
    modernDosage: ["大黄12g", "葶苈子6g", "芒硝6g", "杏仁6g"],
    originalDosage: ["大黄半斤", "葶苈子半升", "芒硝半升", "杏仁半升"],
    indications: ["病发于阳而反下之热入因作结胸病发于阴而反下之因作痞也所以成结胸者以下之太早故也结胸者项亦强如柔痉状下之则和宜大陷胸丸"],
    symptoms: ["项强", "如柔痉状", "胸胁硬满"],
    functions: ["泻热逐水", "破结通便"],
    analysis: ["大黄芒硝泻热通便", "葶苈子杏仁泻肺行水"],
    niNotes: ["大陷胸丸治结胸轻证", "项强如柔痉"],
    contraindications: ["体质虚弱者", "孕妇"],
    modifications: [],
    tongue: "舌红苔黄腻",
    pulse: "沉紧"
  },
  {
    id: "shl-018",
    name: "大陷胸汤",
    pinyin: "Da Xianxiong Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["大黄", "芒硝", "甘遂"],
    modernDosage: ["大黄12g", "芒硝6g", "甘遂1g"],
    originalDosage: ["大黄六两", "芒硝一升", "甘遂一钱匕"],
    indications: ["太阳病脉浮而动数浮则为风数则为热动则为痛数则为虚头痛发热微盗汗出而反恶寒者表未解也医反下之动数变迟膈内拒痛胃中空虚客气动膈短气躁烦心中懊憹阳气内陷心下因硬则为结胸大陷胸汤主之"],
    symptoms: ["心下硬满", "疼痛拒按", "短气躁烦", "心中懊憹"],
    functions: ["泻热逐水", "破结通便"],
    analysis: ["大黄芒硝泻热通便", "甘遂峻下逐水"],
    niNotes: ["大陷胸汤是泻下峻剂", "水热互结的结胸证", "甘遂有毒用量宜小"],
    contraindications: ["体质虚弱者", "孕妇", "表证未解者"],
    modifications: [],
    tongue: "舌红苔黄腻",
    pulse: "沉紧"
  },
  {
    id: "shl-019",
    name: "小陷胸汤",
    pinyin: "Xiao Xianxiong Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["黄连", "半夏", "栝蒌实"],
    modernDosage: ["黄连6g", "半夏9g", "栝蒌实15g"],
    originalDosage: ["黄连一两", "半夏半升", "栝蒌实大者一枚"],
    indications: ["小结胸病正在心下按之则痛脉浮滑者小陷胸汤主之"],
    symptoms: ["心下痞硬", "按之则痛", "脉浮滑"],
    functions: ["清热化痰", "宽胸散结"],
    analysis: ["黄连清热", "半夏化痰", "栝蒌实宽胸散结"],
    niNotes: ["小陷胸汤治小结胸证", "痰热互结"],
    contraindications: ["脾胃虚寒者"],
    modifications: [],
    tongue: "舌红苔黄腻",
    pulse: "浮滑"
  },
  {
    id: "shl-020",
    name: "十枣汤",
    pinyin: "Shizao Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["芫花", "甘遂", "大戟"],
    modernDosage: ["芫花1g", "甘遂1g", "大戟1g"],
    originalDosage: ["芫花熬", "甘遂", "大戟各等分"],
    indications: ["太阳中风下利呕逆表解者乃可攻之其人漐漐汗出发作有时头痛心下痞硬满引胁下痛干呕短气汗出不恶寒者此表解里未和也十枣汤主之"],
    symptoms: ["心下痞硬满", "引胁下痛", "干呕短气", "汗出"],
    functions: ["攻逐水饮"],
    analysis: ["芫花甘遂大戟皆为峻下逐水药"],
    niNotes: ["十枣汤是逐水峻剂", "水饮停聚胸胁", "服法：先煮大枣，再纳药末"],
    contraindications: ["体质虚弱者", "孕妇", "表证未解者"],
    modifications: [],
    tongue: "舌苔白滑",
    pulse: "沉弦"
  },
  {
    id: "shl-021",
    name: "大黄黄连泻心汤",
    pinyin: "Dahuang Huanglian Xiexin Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["大黄", "黄连"],
    modernDosage: ["大黄6g", "黄连3g"],
    originalDosage: ["大黄二两", "黄连一两"],
    indications: ["心下痞按之濡其脉关上浮者大黄黄连泻心汤主之"],
    symptoms: ["心下痞", "按之濡", "脉关上浮"],
    functions: ["泻热消痞"],
    analysis: ["大黄黄连泻热消痞"],
    niNotes: ["热痞证", "大黄黄连清热"],
    contraindications: ["脾胃虚寒者", "孕妇"],
    modifications: [{ condition: "恶寒汗出", modification: "加附子" }],
    tongue: "舌红苔黄",
    pulse: "浮"
  },
  {
    id: "shl-022",
    name: "附子泻心汤",
    pinyin: "Fuzi Xiexin Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["大黄", "黄连", "黄芩", "附子"],
    modernDosage: ["大黄6g", "黄连3g", "黄芩3g", "附子6g"],
    originalDosage: ["大黄二两", "黄连一两", "黄芩一两", "附子一枚"],
    indications: ["心下痞而复恶寒汗出者附子泻心汤主之"],
    symptoms: ["心下痞", "恶寒汗出"],
    functions: ["泻热消痞", "扶阳固表"],
    analysis: ["大黄黄连黄芩泻热消痞", "附子温阳固表"],
    niNotes: ["热痞兼阳虚", "寒热并用"],
    contraindications: [],
    modifications: [],
    tongue: "舌红苔黄",
    pulse: "沉"
  },
  {
    id: "shl-023",
    name: "半夏泻心汤",
    pinyin: "Banxia Xiexin Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["半夏", "黄芩", "干姜", "人参", "黄连", "大枣", "甘草"],
    modernDosage: ["半夏9g", "黄芩6g", "干姜6g", "人参6g", "黄连3g", "大枣4枚", "甘草6g"],
    originalDosage: ["半夏半升", "黄芩三两", "干姜三两", "人参三两", "黄连一两", "大枣十二枚", "甘草三两"],
    indications: ["伤寒五六日呕而发热者柴胡汤证具而以他药下之柴胡证仍在者复与柴胡汤此虽已下之不为逆必蒸蒸而振却发热汗出而解若心下满而硬痛者此为结胸也大陷胸汤主之但满而不痛者此为痞柴胡不中与之宜半夏泻心汤"],
    symptoms: ["心下痞满", "呕吐", "肠鸣", "下利"],
    functions: ["寒热平调", "消痞散结"],
    analysis: ["半夏干姜辛温散寒", "黄芩黄连苦寒清热", "人参大枣甘草益气健脾"],
    niNotes: ["半夏泻心汤治寒热错杂痞证", "心下痞满不痛"],
    contraindications: ["单纯寒证", "单纯热证"],
    modifications: [],
    tongue: "舌苔黄腻",
    pulse: "弦数"
  },
  {
    id: "shl-024",
    name: "生姜泻心汤",
    pinyin: "Shengjiang Xiexin Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["生姜", "甘草", "人参", "干姜", "黄芩", "半夏", "黄连", "大枣"],
    modernDosage: ["生姜12g", "甘草6g", "人参6g", "干姜3g", "黄芩6g", "半夏9g", "黄连3g", "大枣4枚"],
    originalDosage: ["生姜四两", "甘草三两", "人参三两", "干姜一两", "黄芩三两", "半夏半升", "黄连一两", "大枣十二枚"],
    indications: ["伤寒汗出解之后胃中不和心下痞硬干噫食臭胁下有水气腹中雷鸣下利者生姜泻心汤主之"],
    symptoms: ["心下痞硬", "干噫食臭", "腹中雷鸣", "下利"],
    functions: ["和胃消痞", "宣散水气"],
    analysis: ["半夏泻心汤加重生姜用量"],
    niNotes: ["水热互结痞证", "干噫食臭"],
    contraindications: [],
    modifications: [],
    tongue: "舌苔白腻",
    pulse: "弦"
  },
  {
    id: "shl-025",
    name: "甘草泻心汤",
    pinyin: "Gancao Xiexin Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["甘草", "黄芩", "干姜", "半夏", "大枣", "黄连"],
    modernDosage: ["甘草12g", "黄芩6g", "干姜6g", "半夏9g", "大枣4枚", "黄连3g"],
    originalDosage: ["甘草四两", "黄芩三两", "干姜三两", "半夏半升", "大枣十二枚", "黄连一两"],
    indications: ["伤寒中风医反下之其人下利日数十行谷不化腹中雷鸣心下痞硬而满干呕心烦不得安医见心下痞谓病不尽复下之其痞益甚此非结热但以胃中虚客气上逆故使硬也甘草泻心汤主之"],
    symptoms: ["下利日数十行", "谷不化", "腹中雷鸣", "心下痞硬", "干呕心烦"],
    functions: ["益气和胃", "消痞止利"],
    analysis: ["半夏泻心汤加重甘草用量"],
    niNotes: ["脾胃虚弱痞证", "下利频繁"],
    contraindications: [],
    modifications: [],
    tongue: "舌苔薄黄",
    pulse: "缓"
  },
  {
    id: "shl-026",
    name: "旋覆代赭汤",
    pinyin: "Xuanfu Daizhe Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["旋覆花", "人参", "生姜", "代赭石", "甘草", "半夏", "大枣"],
    modernDosage: ["旋覆花9g", "人参6g", "生姜15g", "代赭石6g", "甘草6g", "半夏9g", "大枣4枚"],
    originalDosage: ["旋覆花三两", "人参二两", "生姜五两", "代赭石一两", "甘草三两", "半夏半升", "大枣十二枚"],
    indications: ["伤寒发汗若吐若下解后心下痞硬噫气不除者旋覆代赭汤主之"],
    symptoms: ["心下痞硬", "噫气不除"],
    functions: ["降逆化痰", "益气和胃"],
    analysis: ["旋覆花代赭石降逆化痰", "人参甘草大枣益气和胃"],
    niNotes: ["噫气不除", "胃虚痰阻"],
    contraindications: ["孕妇"],
    modifications: [],
    tongue: "舌苔白滑",
    pulse: "弦"
  },
  {
    id: "shl-027",
    name: "干姜黄芩黄连人参汤",
    pinyin: "Ganjiang Huangqin Huanglian Renshen Tang",
    source: "《伤寒论》",
    chapter: "辨厥阴病脉证并治",
    composition: ["干姜", "黄芩", "黄连", "人参"],
    modernDosage: ["干姜6g", "黄芩6g", "黄连3g", "人参6g"],
    originalDosage: ["干姜三两", "黄芩三两", "黄连三两", "人参三两"],
    indications: ["伤寒本自寒下医复吐下之寒格更逆吐下食入口即吐干姜黄芩黄连人参汤主之"],
    symptoms: ["食入口即吐", "下利"],
    functions: ["苦寒清热", "辛温开结"],
    analysis: ["黄芩黄连苦寒清热", "干姜温中散寒", "人参益气"],
    niNotes: ["上热下寒格拒证"],
    contraindications: [],
    modifications: [],
    tongue: "舌红苔黄",
    pulse: "数"
  },
  {
    id: "shl-028",
    name: "黄连汤",
    pinyin: "Huanglian Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["黄连", "甘草", "干姜", "桂枝", "人参", "半夏", "大枣"],
    modernDosage: ["黄连9g", "甘草6g", "干姜6g", "桂枝6g", "人参6g", "半夏9g", "大枣4枚"],
    originalDosage: ["黄连三两", "甘草三两", "干姜三两", "桂枝三两", "人参二两", "半夏半升", "大枣十二枚"],
    indications: ["伤寒胸中有热胃中有邪气腹中痛欲呕吐者黄连汤主之"],
    symptoms: ["腹中痛", "欲呕吐"],
    functions: ["清上温下", "和胃降逆"],
    analysis: ["黄连清热", "干姜桂枝温中", "人参甘草大枣益气"],
    niNotes: ["上热下寒腹痛呕吐"],
    contraindications: [],
    modifications: [],
    tongue: "舌红苔黄",
    pulse: "弦"
  },
  {
    id: "shl-029",
    name: "黄芩汤",
    pinyin: "Huangqin Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["黄芩", "芍药", "甘草", "大枣"],
    modernDosage: ["黄芩9g", "芍药6g", "甘草6g", "大枣4枚"],
    originalDosage: ["黄芩三两", "芍药二两", "甘草二两", "大枣十二枚"],
    indications: ["太阳与少阳合病自下利者与黄芩汤若呕者黄芩加半夏生姜汤主之"],
    symptoms: ["下利", "腹痛"],
    functions: ["清热止利"],
    analysis: ["黄芩清热", "芍药缓急止痛"],
    niNotes: ["热利"],
    contraindications: ["脾胃虚寒者"],
    modifications: [{ condition: "呕", modification: "加半夏生姜" }],
    tongue: "舌红苔黄",
    pulse: "数"
  },
  {
    id: "shl-030",
    name: "黄芩加半夏生姜汤",
    pinyin: "Huangqin Jia Banxia Shengjiang Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["黄芩", "芍药", "甘草", "大枣", "半夏", "生姜"],
    modernDosage: ["黄芩9g", "芍药6g", "甘草6g", "大枣4枚", "半夏9g", "生姜9g"],
    originalDosage: ["黄芩三两", "芍药二两", "甘草二两", "大枣十二枚", "半夏半升", "生姜一两半"],
    indications: ["太阳与少阳合病自下利者与黄芩汤若呕者黄芩加半夏生姜汤主之"],
    symptoms: ["下利", "呕吐"],
    functions: ["清热止利", "和胃止呕"],
    analysis: ["黄芩汤加半夏生姜"],
    niNotes: ["热利兼呕"],
    contraindications: ["脾胃虚寒者"],
    modifications: [],
    tongue: "舌红苔黄",
    pulse: "数"
  },
  {
    id: "shl-031",
    name: "桂枝人参汤",
    pinyin: "Guizhi Renshen Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治下",
    composition: ["桂枝", "甘草", "白术", "人参", "干姜"],
    modernDosage: ["桂枝9g", "甘草6g", "白术9g", "人参6g", "干姜6g"],
    originalDosage: ["桂枝四两", "甘草四两", "白术三两", "人参三两", "干姜三两"],
    indications: ["太阳病外证未除而数下之遂协热而利利下不止心下痞硬表里不解者桂枝人参汤主之"],
    symptoms: ["下利不止", "心下痞硬", "发热恶寒"],
    functions: ["温中解表"],
    analysis: ["理中汤加桂枝"],
    niNotes: ["表证未解兼里虚寒"],
    contraindications: [],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "沉迟"
  },
  {
    id: "shl-032",
    name: "葛根黄芩黄连汤",
    pinyin: "Gegen Huangqin Huanglian Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["葛根", "甘草", "黄芩", "黄连"],
    modernDosage: ["葛根15g", "甘草6g", "黄芩9g", "黄连9g"],
    originalDosage: ["葛根半斤", "甘草二两", "黄芩三两", "黄连三两"],
    indications: ["太阳病桂枝证医反下之利遂不止脉促者表未解也喘而汗出者葛根黄芩黄连汤主之"],
    symptoms: ["下利", "喘", "汗出", "脉促"],
    functions: ["解表清里"],
    analysis: ["葛根解表", "黄芩黄连清热"],
    niNotes: ["表证未解兼里热"],
    contraindications: ["脾胃虚寒者"],
    modifications: [],
    tongue: "舌红苔黄",
    pulse: "促"
  },
  {
    id: "shl-033",
    name: "干姜附子汤",
    pinyin: "Ganjiang Fuzi Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["干姜", "附子"],
    modernDosage: ["干姜6g", "附子9g"],
    originalDosage: ["干姜一两", "附子一枚"],
    indications: ["下之后复发汗昼日烦躁不得眠夜而安静不呕不渴无表证脉沉微身无大热者干姜附子汤主之"],
    symptoms: ["昼日烦躁不得眠", "夜而安静", "脉沉微"],
    functions: ["急救回阳"],
    analysis: ["干姜附子温阳救逆"],
    niNotes: ["阳虚烦躁"],
    contraindications: ["阴虚阳亢者"],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "沉微"
  },
  {
    id: "shl-034",
    name: "茯苓四逆汤",
    pinyin: "Fuling Sinisan Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["茯苓", "人参", "附子", "甘草", "干姜"],
    modernDosage: ["茯苓12g", "人参6g", "附子9g", "甘草6g", "干姜6g"],
    originalDosage: ["茯苓四两", "人参一两", "附子一枚", "甘草二两", "干姜一两半"],
    indications: ["发汗若下之病仍不解烦躁者茯苓四逆汤主之"],
    symptoms: ["烦躁", "四肢厥冷", "脉沉微"],
    functions: ["回阳益阴"],
    analysis: ["四逆汤加茯苓人参"],
    niNotes: ["阳虚烦躁较甚"],
    contraindications: ["阴虚阳亢者"],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "沉微"
  },
  {
    id: "shl-035",
    name: "四逆汤",
    pinyin: "Sinisan Tang",
    source: "《伤寒论》",
    chapter: "辨少阴病脉证并治",
    composition: ["甘草", "干姜", "附子"],
    modernDosage: ["甘草6g", "干姜9g", "附子9g"],
    originalDosage: ["甘草二两", "干姜一两半", "附子一枚"],
    indications: ["少阴病脉沉者急温之宜四逆汤", "自利不渴者属太阴以其藏有寒故也当温之宜服四逆辈"],
    symptoms: ["四肢厥冷", "下利清谷", "脉沉微"],
    functions: ["回阳救逆"],
    analysis: ["附子干姜温阳", "甘草调和"],
    niNotes: ["四逆汤是回阳救逆的代表方", "三阴证通用"],
    contraindications: ["阴虚阳亢者"],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "沉微"
  },
  {
    id: "shl-036",
    name: "通脉四逆汤",
    pinyin: "Tongmai Sinisan Tang",
    source: "《伤寒论》",
    chapter: "辨少阴病脉证并治",
    composition: ["甘草", "附子", "干姜"],
    modernDosage: ["甘草6g", "附子12g", "干姜12g"],
    originalDosage: ["甘草二两", "附子大者一枚", "干姜三两"],
    indications: ["少阴病下利清谷里寒外热手足厥逆脉微欲绝身反不恶寒其人面色赤或腹痛或干呕或咽痛或利止脉不出者通脉四逆汤主之"],
    symptoms: ["下利清谷", "手足厥逆", "脉微欲绝", "身反不恶寒"],
    functions: ["回阳通脉"],
    analysis: ["四逆汤加重干姜附子用量"],
    niNotes: ["阴盛格阳证"],
    contraindications: ["阴虚阳亢者"],
    modifications: [{ condition: "面色赤", modification: "加葱白" }, { condition: "咽痛", modification: "去芍药加桔梗" }, { condition: "利止脉不出", modification: "去桔梗加人参" }],
    tongue: "舌淡苔白",
    pulse: "微欲绝"
  },
  {
    id: "shl-037",
    name: "通脉四逆加猪胆汁汤",
    pinyin: "Tongmai Sinisan Jia Zhudanzhi Tang",
    source: "《伤寒论》",
    chapter: "辨少阴病脉证并治",
    composition: ["甘草", "附子", "干姜", "猪胆汁"],
    modernDosage: ["甘草6g", "附子12g", "干姜12g", "猪胆汁5ml"],
    originalDosage: ["甘草二两", "附子大者一枚", "干姜三两", "猪胆汁半合"],
    indications: ["吐已下断汗出而厥四肢拘急不解脉微欲绝者通脉四逆加猪胆汁汤主之"],
    symptoms: ["吐下已断", "汗出而厥", "四肢拘急", "脉微欲绝"],
    functions: ["回阳救逆", "益阴和阳"],
    analysis: ["通脉四逆汤加猪胆汁"],
    niNotes: ["阳亡阴竭证"],
    contraindications: ["阴虚阳亢者"],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "微欲绝"
  },
  {
    id: "shl-038",
    name: "白通汤",
    pinyin: "Baitong Tang",
    source: "《伤寒论》",
    chapter: "辨少阴病脉证并治",
    composition: ["葱白", "干姜", "附子"],
    modernDosage: ["葱白4茎", "干姜6g", "附子9g"],
    originalDosage: ["葱白四茎", "干姜一两", "附子一枚"],
    indications: ["少阴病下利白通汤主之"],
    symptoms: ["下利", "四肢厥冷"],
    functions: ["通阳破阴"],
    analysis: ["葱白通阳", "干姜附子温阳"],
    niNotes: ["阴盛阳虚"],
    contraindications: ["阴虚阳亢者"],
    modifications: [{ condition: "干呕烦", modification: "加猪胆汁人尿" }],
    tongue: "舌淡苔白",
    pulse: "沉"
  },
  {
    id: "shl-039",
    name: "白通加猪胆汁汤",
    pinyin: "Baitong Jia Zhudanzhi Tang",
    source: "《伤寒论》",
    chapter: "辨少阴病脉证并治",
    composition: ["葱白", "干姜", "附子", "人尿", "猪胆汁"],
    modernDosage: ["葱白4茎", "干姜6g", "附子9g", "人尿10ml", "猪胆汁5ml"],
    originalDosage: ["葱白四茎", "干姜一两", "附子一枚", "人尿五合", "猪胆汁一合"],
    indications: ["少阴病下利脉微者与白通汤利不止厥逆无脉干呕烦者白通加猪胆汁汤主之服汤脉暴出者死微续者生"],
    symptoms: ["下利不止", "厥逆无脉", "干呕烦"],
    functions: ["破阴回阳", "宣通上下"],
    analysis: ["白通汤加人尿猪胆汁"],
    niNotes: ["阴阳格拒"],
    contraindications: ["阴虚阳亢者"],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "无脉"
  },
  {
    id: "shl-040",
    name: "真武汤",
    pinyin: "Zhenwu Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["茯苓", "芍药", "白术", "生姜", "附子"],
    modernDosage: ["茯苓9g", "芍药9g", "白术6g", "生姜9g", "附子9g"],
    originalDosage: ["茯苓三两", "芍药三两", "白术二两", "生姜三两", "附子一枚"],
    indications: ["太阳病发汗汗出不解其人仍发热心下悸头眩身瞤动振振欲擗地者真武汤主之", "少阴病二三日不已至四五日腹痛小便不利四肢沉重疼痛自下利者此为有水气其人或咳或小便利或下利或呕者真武汤主之"],
    symptoms: ["心下悸", "头眩", "身瞤动", "四肢沉重疼痛"],
    functions: ["温阳利水"],
    analysis: ["附子温阳", "茯苓白术利水", "芍药敛阴"],
    niNotes: ["阳虚水泛"],
    contraindications: ["阴虚阳亢者"],
    modifications: [{ condition: "咳", modification: "加五味子细辛干姜" }, { condition: "小便利", modification: "去茯苓" }, { condition: "下利", modification: "去芍药加干姜" }, { condition: "呕", modification: "去附子加生姜" }],
    tongue: "舌淡苔白滑",
    pulse: "沉"
  },
  {
    id: "shl-041",
    name: "附子汤",
    pinyin: "Fuzi Tang",
    source: "《伤寒论》",
    chapter: "辨少阴病脉证并治",
    composition: ["附子", "茯苓", "人参", "白术", "芍药"],
    modernDosage: ["附子9g", "茯苓9g", "人参6g", "白术12g", "芍药9g"],
    originalDosage: ["附子二枚", "茯苓三两", "人参二两", "白术四两", "芍药三两"],
    indications: ["少阴病得之一二日口中和其背恶寒者当灸之附子汤主之", "少阴病身体痛手足寒骨节痛脉沉者附子汤主之"],
    symptoms: ["身体痛", "手足寒", "骨节痛", "脉沉"],
    functions: ["温阳益气", "散寒除湿"],
    analysis: ["附子温阳", "人参白术益气", "茯苓利水"],
    niNotes: ["阳虚寒湿"],
    contraindications: ["阴虚阳亢者"],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "沉"
  },
  {
    id: "shl-042",
    name: "桃花汤",
    pinyin: "Taohua Tang",
    source: "《伤寒论》",
    chapter: "辨少阴病脉证并治",
    composition: ["赤石脂", "干姜", "粳米"],
    modernDosage: ["赤石脂30g", "干姜6g", "粳米15g"],
    originalDosage: ["赤石脂一斤", "干姜一两", "粳米一升"],
    indications: ["少阴病下利便脓血者桃花汤主之"],
    symptoms: ["下利", "便脓血"],
    functions: ["温中涩肠"],
    analysis: ["赤石脂涩肠", "干姜温中", "粳米益气"],
    niNotes: ["虚寒下利脓血"],
    contraindications: ["热利"],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "沉迟"
  },
  {
    id: "shl-043",
    name: "吴茱萸汤",
    pinyin: "Wuzhuyu Tang",
    source: "《伤寒论》",
    chapter: "辨阳明病脉证并治",
    composition: ["吴茱萸", "人参", "生姜", "大枣"],
    modernDosage: ["吴茱萸6g", "人参6g", "生姜15g", "大枣4枚"],
    originalDosage: ["吴茱萸一升", "人参三两", "生姜六两", "大枣十二枚"],
    indications: ["食谷欲呕属阳明也吴茱萸汤主之得汤反剧者属上焦也", "少阴病吐利手足逆冷烦躁欲死者吴茱萸汤主之", "干呕吐涎沫头痛者吴茱萸汤主之"],
    symptoms: ["呕吐", "头痛", "手足逆冷", "烦躁"],
    functions: ["温中补虚", "降逆止呕"],
    analysis: ["吴茱萸温中降逆", "人参大枣益气", "生姜止呕"],
    niNotes: ["肝胃虚寒"],
    contraindications: ["肝阳上亢者"],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "沉迟"
  },
  {
    id: "shl-044",
    name: "当归四逆汤",
    pinyin: "Danggui Sinisan Tang",
    source: "《伤寒论》",
    chapter: "辨厥阴病脉证并治",
    composition: ["当归", "桂枝", "芍药", "细辛", "甘草", "通草", "大枣"],
    modernDosage: ["当归9g", "桂枝9g", "芍药9g", "细辛3g", "甘草6g", "通草6g", "大枣4枚"],
    originalDosage: ["当归三两", "桂枝三两", "芍药三两", "细辛三两", "甘草二两", "通草二两", "大枣二十五枚"],
    indications: ["手足厥寒脉细欲绝者当归四逆汤主之"],
    symptoms: ["手足厥寒", "脉细欲绝"],
    functions: ["温经散寒", "养血通脉"],
    analysis: ["当归芍药养血", "桂枝细辛温通"],
    niNotes: ["血虚寒厥"],
    contraindications: ["阴虚阳亢者"],
    modifications: [{ condition: "内有久寒", modification: "加吴茱萸生姜" }],
    tongue: "舌淡苔白",
    pulse: "细"
  },
  {
    id: "shl-045",
    name: "当归四逆加吴茱萸生姜汤",
    pinyin: "Danggui Sinisan Jia Wuzhuyu Shengjiang Tang",
    source: "《伤寒论》",
    chapter: "辨厥阴病脉证并治",
    composition: ["当归", "桂枝", "芍药", "细辛", "甘草", "通草", "大枣", "吴茱萸", "生姜"],
    modernDosage: ["当归9g", "桂枝9g", "芍药9g", "细辛3g", "甘草6g", "通草6g", "大枣4枚", "吴茱萸6g", "生姜15g"],
    originalDosage: ["当归三两", "桂枝三两", "芍药三两", "细辛三两", "甘草二两", "通草二两", "大枣二十五枚", "吴茱萸二升", "生姜半斤"],
    indications: ["若其人内有久寒者宜当归四逆加吴茱萸生姜汤"],
    symptoms: ["手足厥寒", "脉细欲绝", "内有久寒"],
    functions: ["温经散寒", "养血通脉", "温中祛寒"],
    analysis: ["当归四逆汤加吴茱萸生姜"],
    niNotes: ["血虚寒厥兼内有久寒"],
    contraindications: ["阴虚阳亢者"],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "细"
  },
  {
    id: "shl-046",
    name: "黄芪桂枝五物汤",
    pinyin: "Huangqi Guizhi Wuwu Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治",
    composition: ["黄芪", "芍药", "桂枝", "生姜", "大枣"],
    modernDosage: ["黄芪9g", "芍药9g", "桂枝9g", "生姜18g", "大枣4枚"],
    originalDosage: ["黄芪三两", "芍药三两", "桂枝三两", "生姜六两", "大枣十二枚"],
    indications: ["血痹阴阳俱微寸口关上微尺中小紧外证身体不仁如风痹状黄芪桂枝五物汤主之"],
    symptoms: ["身体不仁", "如风痹状"],
    functions: ["益气温经", "和血通痹"],
    analysis: ["黄芪益气", "桂枝芍药调和营卫"],
    niNotes: ["血痹"],
    contraindications: [],
    modifications: [],
    tongue: "舌淡苔白",
    pulse: "微"
  },
  {
    id: "shl-047",
    name: "炙甘草汤",
    pinyin: "Zhigancao Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治中",
    composition: ["甘草", "生姜", "人参", "生地黄", "桂枝", "阿胶", "麦冬", "麻仁", "大枣"],
    modernDosage: ["甘草12g", "生姜9g", "人参6g", "生地黄30g", "桂枝9g", "阿胶6g", "麦冬15g", "麻仁15g", "大枣6枚"],
    originalDosage: ["甘草四两", "生姜三两", "人参二两", "生地黄一斤", "桂枝三两", "阿胶二两", "麦冬半升", "麻仁半升", "大枣三十枚"],
    indications: ["伤寒脉结代心动悸炙甘草汤主之"],
    symptoms: ["脉结代", "心动悸"],
    functions: ["滋阴养血", "益气温阳"],
    analysis: ["生地麦冬阿胶麻仁滋阴养血", "人参桂枝生姜甘草温阳益气"],
    niNotes: ["炙甘草汤是治脉结代心动悸的要方", "又名复脉汤"],
    contraindications: ["脾胃虚寒者"],
    modifications: [],
    tongue: "舌红少苔",
    pulse: "结代"
  },
  {
    id: "shl-048",
    name: "酸枣仁汤",
    pinyin: "Suanzaoren Tang",
    source: "《伤寒论》",
    chapter: "辨太阳病脉证并治",
    composition: ["酸枣仁", "甘草", "知母", "茯苓", "川芎"],
    modernDosage: ["酸枣仁15g", "甘草3g", "知母6g", "茯苓6g", "川芎6g"],
    originalDosage: ["酸枣仁二升", "甘草一两", "知母二两", "茯苓二两", "川芎二两"],
    indications: ["虚劳虚烦不得眠酸枣仁汤主之"],
    symptoms: ["虚烦不得眠"],
    functions: ["养血安神", "清热除烦"],
    analysis: ["酸枣仁养血安神", "知母清热除烦"],
    niNotes: ["虚烦失眠"],
    contraindications: [],
    modifications: [],
    tongue: "舌红少苔",
    pulse: "细数"
  },
  {
    id: "shl-049",
    name: "黄连阿胶汤",
    pinyin: "Huanglian Ejiao Tang",
    source: "《伤寒论》",
    chapter: "辨少阴病脉证并治",
    composition: ["黄连", "黄芩", "芍药", "鸡子黄", "阿胶"],
    modernDosage: ["黄连9g", "黄芩6g", "芍药6g", "鸡子黄2枚", "阿胶6g"],
    originalDosage: ["黄连四两", "黄芩二两", "芍药二两", "鸡子黄二枚", "阿胶三两"],
    indications: ["少阴病得之二三日以上心中烦不得卧黄连阿胶汤主之"],
    symptoms: ["心中烦", "不得卧"],
    functions: ["滋阴降火", "除烦安神"],
    analysis: ["黄连黄芩清热", "阿胶鸡子黄滋阴"],
    niNotes: ["阴虚火旺"],
    contraindications: ["脾胃虚寒者"],
    modifications: [],
    tongue: "舌红少苔",
    pulse: "细数"
  },
  {
    id: "shl-050",
    name: "栀子柏皮汤",
    pinyin: "Zhizi Baipi Tang",
    source: "《伤寒论》",
    chapter: "辨阳明病脉证并治",
    composition: ["栀子", "甘草", "黄柏"],
    modernDosage: ["栀子9g", "甘草6g", "黄柏6g"],
    originalDosage: ["栀子十五个", "甘草一两", "黄柏二两"],
    indications: ["伤寒身黄发热栀子柏皮汤主之"],
    symptoms: ["身黄", "发热"],
    functions: ["清热利湿"],
    analysis: ["栀子黄柏清热利湿"],
    niNotes: ["湿热黄疸"],
    contraindications: ["寒湿黄疸"],
    modifications: [],
    tongue: "舌红苔黄腻",
    pulse: "数"
  },
  {
    id: "shl-051",
    name: "麻黄连轺赤小豆汤",
    pinyin: "Mahuang Lianqiao Chixiaodou Tang",
    source: "《伤寒论》",
    chapter: "辨阳明病脉证并治",
    composition: ["麻黄", "连轺", "杏仁", "赤小豆", "大枣", "生梓白皮", "生姜", "甘草"],
    modernDosage: ["麻黄6g", "连轺6g", "杏仁6g", "赤小豆30g", "大枣4枚", "生梓白皮15g", "生姜6g", "甘草6g"],
    originalDosage: ["麻黄二两", "连轺二两", "杏仁四十个", "赤小豆一升", "大枣十二枚", "生梓白皮切一升", "生姜二两", "甘草二两"],
    indications: ["伤寒瘀热在里身必发黄麻黄连轺赤小豆汤主之"],
    symptoms: ["身黄", "发热", "无汗"],
    functions: ["解表散邪", "清热利湿"],
    analysis: ["麻黄解表", "赤小豆连轺清热利湿"],
    niNotes: ["表证未解兼湿热黄疸"],
    contraindications: ["表虚有汗者"],
    modifications: [],
    tongue: "舌红苔黄腻",
    pulse: "浮"
  },
  {
    id: "shl-052",
    name: "茵陈蒿汤",
    pinyin: "Yinchenhao Tang",
    source: "《伤寒论》",
    chapter: "辨阳明病脉证并治",
    composition: ["茵陈", "栀子", "大黄"],
    modernDosage: ["茵陈18g", "栀子9g", "大黄6g"],
    originalDosage: ["茵陈六两", "栀子十四枚", "大黄二两"],
    indications: ["阳明病发热汗出者此为热越不能发黄也但头汗出身无汗剂颈而还小便不利渴引水浆者此为瘀热在里身必发黄茵陈蒿汤主之"],
    symptoms: ["身黄", "小便不利", "渴引水浆"],
    functions: ["清热利湿", "退黄"],
    analysis: ["茵陈清热利湿退黄", "栀子大黄清热通便"],
    niNotes: ["茵陈蒿汤是治黄疸的要方", "阳黄"],
    contraindications: ["寒湿黄疸"],
    modifications: [],
    tongue: "舌红苔黄腻",
    pulse: "滑数"
  },
  {
    id: "shl-053",
    name: "麻子仁丸",
    pinyin: "Maziren Wan",
    source: "《伤寒论》",
    chapter: "辨阳明病脉证并治",
    composition: ["麻子仁", "杏仁", "大黄", "厚朴", "枳实", "芍药"],
    modernDosage: ["麻子仁15g", "杏仁9g", "大黄6g", "厚朴6g", "枳实6g", "芍药9g"],
    originalDosage: ["麻子仁二升", "杏仁一升", "大黄一斤", "厚朴一尺", "枳实半斤", "芍药半斤"],
    indications: ["趺阳脉浮而涩浮则胃气强涩则小便数浮涩相搏大便则硬其脾为约麻子仁丸主之"],
    symptoms: ["大便硬", "小便数"],
    functions: ["润肠泄热", "行气通便"],
    analysis: ["麻子仁杏仁润肠", "大黄通便", "厚朴枳实行气"],
    niNotes: ["脾约证"],
    contraindications: ["虚寒便秘"],
    modifications: [],
    tongue: "舌红苔黄",
    pulse: "浮涩"
  },
  {
    id: "shl-054",
    name: "蜜煎导方",
    pinyin: "