// 足太阳膀胱经 (67穴)
import { Acupoint } from './types'

export const BLADDER_MERIDIAN: Acupoint[] = [
  { id: "BL1", name: "睛明", pinyin: "jingming", code: "BL1", position: [0.05, 2.02, 0.40], meridian: "足太阳膀胱经", category: "正经", location: "面部，目内眦角稍上方凹陷处", effect: "疏风清热，通络明目", method: "直刺", depth: "0.3-0.5寸", caution: "不可提插，闭眼进针" },
  { id: "BL2", name: "攒竹", pinyin: "cuanzhu", code: "BL2", position: [0.08, 2.08, 0.38], meridian: "足太阳膀胱经", category: "正经", location: "面部，眉头凹陷中，眶上切迹处", effect: "疏风清热，通络明目", method: "平刺或斜刺", depth: "0.3-0.5寸" },
  { id: "BL3", name: "眉冲", pinyin: "meichong", code: "BL3", position: [0.06, 2.15, 0.35], meridian: "足太阳膀胱经", category: "正经", location: "头部，攒竹直上入发际0.5寸", effect: "疏风清热，镇惊安神", method: "平刺", depth: "0.3-0.5寸" },
  { id: "BL4", name: "曲差", pinyin: "qucha", code: "BL4", position: [0.06, 2.20, 0.32], meridian: "足太阳膀胱经", category: "正经", location: "头部，神庭旁1.5寸，入发际0.5寸", effect: "清热明目，安神利窍", method: "平刺", depth: "0.3-0.5寸" },
  { id: "BL5", name: "五处", pinyin: "wuchu", code: "BL5", position: [0.06, 2.25, 0.28], meridian: "足太阳膀胱经", category: "正经", location: "头部，曲差后0.5寸", effect: "清热散风，明目镇痉", method: "平刺", depth: "0.3-0.5寸" },
  { id: "BL6", name: "承光", pinyin: "chengguang", code: "BL6", position: [0.06, 2.32, 0.22], meridian: "足太阳膀胱经", category: "正经", location: "头部，五处后1.5寸", effect: "清热明目，祛风止痛", method: "平刺", depth: "0.3-0.5寸" },
  { id: "BL7", name: "通天", pinyin: "tongtian", code: "BL7", position: [0.06, 2.38, 0.15], meridian: "足太阳膀胱经", category: "正经", location: "头部，承光后1.5寸", effect: "清热散风，通利鼻窍", method: "平刺", depth: "0.3-0.5寸" },
  { id: "BL8", name: "络却", pinyin: "luoque", code: "BL8", position: [0.06, 2.42, 0.08], meridian: "足太阳膀胱经", category: "正经", location: "头部，通天后1.5寸", effect: "清热安神，平肝熄风", method: "平刺", depth: "0.3-0.5寸" },
  { id: "BL9", name: "玉枕", pinyin: "yuzhen", code: "BL9", position: [0.06, 2.35, -0.02], meridian: "足太阳膀胱经", category: "正经", location: "后头部，枕外隆凸上缘旁开1.3寸", effect: "清热明目，通络止痛", method: "平刺", depth: "0.3-0.5寸" },
  { id: "BL10", name: "天柱", pinyin: "tianzhu", code: "BL10", position: [0.06, 1.92, -0.12], meridian: "足太阳膀胱经", category: "正经", location: "项部，后发际正中直上0.5寸，旁开1.3寸", effect: "清头明目，强筋骨", method: "直刺或斜刺", depth: "0.5-1寸" },
  { id: "BL11", name: "大杼", pinyin: "dazhu", code: "BL11", position: [0.06, 1.70, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第1胸椎棘突下，旁开1.5寸", effect: "强筋骨，清邪热", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL12", name: "风门", pinyin: "fengmen", code: "BL12", position: [0.06, 1.65, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第2胸椎棘突下，旁开1.5寸", effect: "祛风解表，宣肺理气", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL13", name: "肺俞", pinyin: "feishu", code: "BL13", position: [0.06, 1.60, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第3胸椎棘突下，旁开1.5寸", effect: "养阴清肺，补虚止咳", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL14", name: "厥阴俞", pinyin: "jueyinshu", code: "BL14", position: [0.06, 1.55, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第4胸椎棘突下，旁开1.5寸", effect: "宁心安神，理气宽胸", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL15", name: "心俞", pinyin: "xinshu", code: "BL15", position: [0.06, 1.50, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第5胸椎棘突下，旁开1.5寸", effect: "养心安神，宽胸理气", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL16", name: "督俞", pinyin: "dushu", code: "BL16", position: [0.06, 1.45, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第6胸椎棘突下，旁开1.5寸", effect: "理气宽胸，强心通脉", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL17", name: "膈俞", pinyin: "geshu", code: "BL17", position: [0.06, 1.40, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第7胸椎棘突下，旁开1.5寸", effect: "养血和血，宽胸理气", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL18", name: "肝俞", pinyin: "ganshu", code: "BL18", position: [0.06, 1.32, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第9胸椎棘突下，旁开1.5寸", effect: "疏肝利胆，理气明目", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL19", name: "胆俞", pinyin: "danshu", code: "BL19", position: [0.06, 1.28, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第10胸椎棘突下，旁开1.5寸", effect: "疏肝利胆，清热化湿", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL20", name: "脾俞", pinyin: "pishu", code: "BL20", position: [0.06, 1.20, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第11胸椎棘突下，旁开1.5寸", effect: "健脾利湿，和胃降逆", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL21", name: "胃俞", pinyin: "weishu", code: "BL21", position: [0.06, 1.15, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "背部，第12胸椎棘突下，旁开1.5寸", effect: "和胃健脾，理气消滞", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL22", name: "三焦俞", pinyin: "sanjiaoshu", code: "BL22", position: [0.06, 1.08, -0.18], meridian: "足太阳膀胱经", category: "正经", location: "腰部，第1腰椎棘突下，旁开1.5寸", effect: "调理三焦，利水消肿", method: "直刺", depth: "0.5-1寸" },
  { id: "BL23", name: "肾俞", pinyin: "shenshu", code: "BL23", position: [0.06, 1.00, -0.18], meridian: "足太阳膀胱经", category: "正经", location: "腰部，第2腰椎棘突下，旁开1.5寸", effect: "补肾助阳，强腰利水", method: "直刺", depth: "0.5-1寸" },
  { id: "BL24", name: "气海俞", pinyin: "qihaishu", code: "BL24", position: [0.06, 0.95, -0.18], meridian: "足太阳膀胱经", category: "正经", location: "腰部，第3腰椎棘突下，旁开1.5寸", effect: "补肾强腰，调经止痛", method: "直刺", depth: "0.5-1寸" },
  { id: "BL25", name: "大肠俞", pinyin: "dachangshu", code: "BL25", position: [0.06, 0.88, -0.18], meridian: "足太阳膀胱经", category: "正经", location: "腰部，第4腰椎棘突下，旁开1.5寸", effect: "理气止痛，调肠通便", method: "直刺", depth: "0.5-1寸" },
  { id: "BL26", name: "关元俞", pinyin: "guanyuanshu", code: "BL26", position: [0.06, 0.82, -0.18], meridian: "足太阳膀胱经", category: "正经", location: "腰部，第5腰椎棘突下，旁开1.5寸", effect: "培补元气，调理下焦", method: "直刺", depth: "0.5-1寸" },
  { id: "BL27", name: "小肠俞", pinyin: "xiaochangshu", code: "BL27", position: [0.06, 0.72, -0.15], meridian: "足太阳膀胱经", category: "正经", location: "骶部，第1骶椎棘突下，旁开1.5寸", effect: "清热利湿，通调二便", method: "直刺", depth: "0.5-1寸" },
  { id: "BL28", name: "膀胱俞", pinyin: "pangguangshu", code: "BL28", position: [0.06, 0.65, -0.15], meridian: "足太阳膀胱经", category: "正经", location: "骶部，第2骶椎棘突下，旁开1.5寸", effect: "清热利湿，通调膀胱", method: "直刺", depth: "0.5-1寸" },
  { id: "BL29", name: "中膂俞", pinyin: "zhonglvshu", code: "BL29", position: [0.06, 0.58, -0.15], meridian: "足太阳膀胱经", category: "正经", location: "骶部，第3骶椎棘突下，旁开1.5寸", effect: "清热利湿，强腰利尿", method: "直刺", depth: "0.5-1寸" },
  { id: "BL30", name: "白环俞", pinyin: "baihuanshu", code: "BL30", position: [0.06, 0.52, -0.15], meridian: "足太阳膀胱经", category: "正经", location: "骶部，第4骶椎棘突下，旁开1.5寸", effect: "调经止带，强腰利湿", method: "直刺", depth: "0.5-1寸" },
  { id: "BL31", name: "上髎", pinyin: "shangliao", code: "BL31", position: [0.04, 0.72, -0.12], meridian: "足太阳膀胱经", category: "正经", location: "骶部，第1骶后孔中", effect: "调经止带，通利二便", method: "直刺", depth: "0.5-1寸" },
  { id: "BL32", name: "次髎", pinyin: "ciliao", code: "BL32", position: [0.04, 0.65, -0.12], meridian: "足太阳膀胱经", category: "正经", location: "骶部，第2骶后孔中", effect: "调经止带，通利二便", method: "直刺", depth: "0.5-1寸" },
  { id: "BL33", name: "中髎", pinyin: "zhongliao", code: "BL33", position: [0.04, 0.58, -0.12], meridian: "足太阳膀胱经", category: "正经", location: "骶部，第3骶后孔中", effect: "调经止带，通利二便", method: "直刺", depth: "0.5-1寸" },
  { id: "BL34", name: "下髎", pinyin: "xialiao", code: "BL34", position: [0.04, 0.52, -0.12], meridian: "足太阳膀胱经", category: "正经", location: "骶部，第4骶后孔中", effect: "调经止带，通利二便", method: "直刺", depth: "0.5-1寸" },
  { id: "BL35", name: "会阳", pinyin: "huiyang", code: "BL35", position: [0.04, 0.46, -0.10], meridian: "足太阳膀胱经", category: "正经", location: "骶部，尾骨端旁开0.5寸", effect: "清热利湿，益肾固脱", method: "直刺", depth: "0.5-1寸" },
  { id: "BL36", name: "承扶", pinyin: "chengfu", code: "BL36", position: [0.12, 0.42, -0.08], meridian: "足太阳膀胱经", category: "正经", location: "股后区，臀沟中点", effect: "舒筋活络，消痔止痛", method: "直刺", depth: "1-2寸" },
  { id: "BL37", name: "殷门", pinyin: "yinmen", code: "BL37", position: [0.12, 0.25, -0.06], meridian: "足太阳膀胱经", category: "正经", location: "股后区，承扶下6寸", effect: "舒筋通络，强腰膝", method: "直刺", depth: "1-2寸" },
  { id: "BL38", name: "浮郄", pinyin: "fuxi", code: "BL38", position: [0.14, 0.12, -0.04], meridian: "足太阳膀胱经", category: "正经", location: "腘横纹外侧端，股二头肌腱内侧", effect: "舒筋活络，清热利湿", method: "直刺", depth: "0.5-1寸" },
  { id: "BL39", name: "委阳", pinyin: "weiyang", code: "BL39", position: [0.15, 0.10, -0.02], meridian: "足太阳膀胱经", category: "正经", location: "腘横纹外侧端，股二头肌腱内侧缘", effect: "舒筋利节，通利三焦", method: "直刺", depth: "0.5-1寸" },
  { id: "BL40", name: "委中", pinyin: "weizhong", code: "BL40", position: [0.12, 0.08, -0.02], meridian: "足太阳膀胱经", category: "正经", location: "腘窝横纹中点", effect: "清热解毒，舒筋通络", method: "直刺或点刺出血", depth: "0.5-1寸" },
  { id: "BL41", name: "附分", pinyin: "fufen", code: "BL41", position: [0.12, 1.65, -0.22], meridian: "足太阳膀胱经", category: "正经", location: "背部，第2胸椎棘突下，旁开3寸", effect: "疏风散邪，舒筋活络", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL42", name: "魄户", pinyin: "pohu", code: "BL42", position: [0.12, 1.60, -0.22], meridian: "足太阳膀胱经", category: "正经", location: "背部，第3胸椎棘突下，旁开3寸", effect: "宣肺止咳，宁心安神", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL43", name: "膏肓", pinyin: "gaohuang", code: "BL43", position: [0.12, 1.55, -0.22], meridian: "足太阳膀胱经", category: "正经", location: "背部，第4胸椎棘突下，旁开3寸", effect: "补虚益损，调理肺气", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL44", name: "神堂", pinyin: "shentang", code: "BL44", position: [0.12, 1.50, -0.22], meridian: "足太阳膀胱经", category: "正经", location: "背部，第5胸椎棘突下，旁开3寸", effect: "宁心安神，宽胸理气", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL45", name: "譩譆", pinyin: "yixi", code: "BL45", position: [0.12, 1.45, -0.22], meridian: "足太阳膀胱经", category: "正经", location: "背部，第6胸椎棘突下，旁开3寸", effect: "清热止咳，安神定志", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL46", name: "膈关", pinyin: "geguan", code: "BL46", position: [0.12, 1.40, -0.22], meridian: "足太阳膀胱经", category: "正经", location: "背部，第7胸椎棘突下，旁开3寸", effect: "宽胸利膈，和胃降逆", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL47", name: "魂门", pinyin: "hunmen", code: "BL47", position: [0.12, 1.32, -0.22], meridian: "足太阳膀胱经", category: "正经", location: "背部，第9胸椎棘突下，旁开3寸", effect: "疏肝理气，健脾和胃", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL48", name: "阳纲", pinyin: "yanggang", code: "BL48", position: [0.12, 1.28, -0.22], meridian: "足太阳膀胱经", category: "正经", location: "背部，第10胸椎棘突下，旁开3寸", effect: "疏肝利胆，清热利湿", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL49", name: "意舍", pinyin: "yishe", code: "BL49", position: [0.12, 1.20, -0.22], meridian: "足太阳膀胱经", category: "正经", location: "背部，第11胸椎棘突下，旁开3寸", effect: "健脾和胃，利湿消肿", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL50", name: "胃仓", pinyin: "weicang", code: "BL50", position: [0.12, 1.15, -0.22], meridian: "足太阳膀胱经", category: "正经", location: "背部，第12胸椎棘突下，旁开3寸", effect: "和胃健脾，消食导滞", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL51", name: "肓门", pinyin: "huangmen", code: "BL51", position: [0.12, 1.08, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "腰部，第1腰椎棘突下，旁开3寸", effect: "理气消结，清热散结", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL52", name: "志室", pinyin: "zhishi", code: "BL52", position: [0.12, 1.00, -0.20], meridian: "足太阳膀胱经", category: "正经", location: "腰部，第2腰椎棘突下，旁开3寸", effect: "益肾固精，清热利湿", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "BL53", name: "胞肓", pinyin: "baohuang", code: "BL53", position: [0.12, 0.65, -0.18], meridian: "足太阳膀胱经", category: "正经", location: "骶部，第2骶椎棘突下，旁开3寸", effect: "通利二便，强腰补肾", method: "直刺", depth: "0.5-1寸" },
  { id: "BL54", name: "秩边", pinyin: "zhibian", code: "BL54", position: [0.12, 0.52, -0.15], meridian: "足太阳膀胱经", category: "正经", location: "骶部，第4骶椎棘突下，旁开3寸", effect: "舒筋活络，强腰利湿", method: "直刺", depth: "1-2寸" },
  { id: "BL55", name: "合阳", pinyin: "heyang", code: "BL55", position: [0.12, 0.02, -0.04], meridian: "足太阳膀胱经", category: "正经", location: "小腿后面，腘横纹下2寸", effect: "舒筋通络，调经止痛", method: "直刺", depth: "0.5-1寸" },
  { id: "BL56", name: "承筋", pinyin: "chengjin", code: "BL56", position: [0.12, -0.08, -0.06], meridian: "足太阳膀胱经", category: "正经", location: "小腿后面，腘横纹下5寸，腓肠肌两肌腹之间", effect: "舒筋活络，清热止痛", method: "直刺", depth: "0.5-1寸" },
  { id: "BL57", name: "承山", pinyin: "chengshan", code: "BL57", position: [0.12, -0.18, -0.08], meridian: "足太阳膀胱经", category: "正经", location: "小腿后面，腓肠肌两肌腹交界下方尖角凹陷处", effect: "理气止痛，舒筋活络，消痔止痛", method: "直刺", depth: "0.5-1.5寸" },
  { id: "BL58", name: "飞扬", pinyin: "feiyang", code: "BL58", position: [0.14, -0.22, -0.06], meridian: "足太阳膀胱经", category: "正经", location: "小腿后外侧，承山穴外下方1寸", effect: "清热安神，舒筋活络", method: "直刺", depth: "0.5-1寸" },
  { id: "BL59", name: "跗阳", pinyin: "fuyang", code: "BL59", position: [0.14, -0.35, -0.04], meridian: "足太阳膀胱经", category: "正经", location: "小腿后外侧，外踝尖上3寸", effect: "舒筋活络，清热安神", method: "直刺", depth: "0.5-1寸" },
  { id: "BL60", name: "昆仑", pinyin: "kunlun", code: "BL60", position: [0.14, -0.48, -0.02], meridian: "足太阳膀胱经", category: "正经", location: "足外踝后方，外踝尖与跟腱之间凹陷中", effect: "舒筋活络，清热安神，引产", method: "直刺", depth: "0.3-0.5寸", caution: "孕妇禁针" },
  { id: "BL61", name: "仆参", pinyin: "pucan", code: "BL61", position: [0.12, -0.52, -0.04], meridian: "足太阳膀胱经", category: "正经", location: "足外侧部，昆仑直下，跟骨外侧凹陷处", effect: "舒筋健骨，清热安神", method: "直刺", depth: "0.3-0.5寸" },
  { id: "BL62", name: "申脉", pinyin: "shenmai", code: "BL62", position: [0.14, -0.50, 0.0], meridian: "足太阳膀胱经", category: "正经", location: "足外侧部，外踝直下方凹陷中", effect: "宁心安神，舒筋活络", method: "直刺", depth: "0.3-0.5寸" },
  { id: "BL63", name: "金门", pinyin: "jinmen", code: "BL63", position: [0.16, -0.55, 0.02], meridian: "足太阳膀胱经", category: "正经", location: "足外侧部，外踝前缘直下，骰骨下缘凹陷处", effect: "安神定志，舒筋活络", method: "直刺", depth: "0.3-0.5寸" },
  { id: "BL64", name: "京骨", pinyin: "jinggu", code: "BL64", position: [0.18, -0.58, 0.04], meridian: "足太阳膀胱经", category: "正经", location: "足外侧部，第5跖骨粗隆下方凹陷处", effect: "清热止痉，明目舒筋", method: "直刺", depth: "0.3-0.5寸" },
  { id: "BL65", name: "束骨", pinyin: "shugu", code: "BL65", position: [0.19, -0.62, 0.06], meridian: "足太阳膀胱经", category: "正经", location: "足外侧部，第5跖趾关节后方凹陷处", effect: "清热散风，舒筋活络", method: "直刺", depth: "0.3-0.5寸" },
  { id: "BL66", name: "足通谷", pinyin: "zutonggu", code: "BL66", position: [0.20, -0.66, 0.08], meridian: "足太阳膀胱经", category: "正经", location: "足外侧部，第5跖趾关节前方凹陷处", effect: "清热安神，止痛止血", method: "直刺", depth: "0.2-0.3寸" },
  { id: "BL67", name: "至阴", pinyin: "zhiyin", code: "BL67", position: [0.20, -0.70, 0.10], meridian: "足太阳膀胱经", category: "正经", location: "足小趾末节外侧，距趾甲角0.1寸", effect: "正胎催产，清头明目", method: "浅刺", depth: "0.1寸或灸" },
]
