// 足少阳胆经 - 44穴
import { Acupoint } from "./types"

export const gallbladderMeridian: Acupoint[] = [
  { id: "GB1", name: "瞳子髎", pinyin: "Tongziliao", meridian: "足少阳胆经", code: "GB", location: "面部，目外眦旁0.5寸凹陷处", position: [-0.05, 0.86, 0.1], indication: "头痛、目赤肿痛、目翳、青盲、迎风流泪、口眼歪斜", method: "平刺0.3-0.5寸", category: "" },
  { id: "GB2", name: "听会", pinyin: "Tinghui", meridian: "足少阳胆经", code: "GB", location: "面部，耳屏间切迹前方，下颌骨髁状突后缘", position: [-0.05, 0.81, 0.09], indication: "耳聋、耳鸣、齿痛、口眼歪斜、面痛、下颌脱臼", method: "直刺0.5-1寸", category: "" },
  { id: "GB3", name: "上关", pinyin: "Shangguan", meridian: "足少阳胆经", code: "GB", location: "耳前，下关直上，颧弓上缘凹陷处", position: [-0.05, 0.84, 0.1], indication: "头痛、耳聋、耳鸣、口眼歪斜、齿痛", method: "直刺0.5-0.8寸", category: "" },
  { id: "GB4", name: "颔厌", pinyin: "Hanyan", meridian: "足少阳胆经", code: "GB", location: "头部，从头维至曲鬓的弧形连线上1/4与下3/4交点处", position: [-0.04, 0.88, 0.08], indication: "头痛、眩晕、目外眦痛、耳鸣、惊痫", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB5", name: "悬颅", pinyin: "Xuanlu", meridian: "足少阳胆经", code: "GB", location: "头部，从头维至曲鬓的弧形连线中点", position: [-0.03, 0.89, 0.06], indication: "偏头痛、目赤肿痛、齿痛", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB6", name: "悬厘", pinyin: "Xuanli", meridian: "足少阳胆经", code: "GB", location: "头部，从头维至曲鬓的弧形连线上3/4与下1/4交点处", position: [-0.02, 0.9, 0.04], indication: "偏头痛、目外眦痛、耳鸣", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB7", name: "曲鬓", pinyin: "Qubin", meridian: "足少阳胆经", code: "GB", location: "头部，耳前鬓角发际后缘与耳尖水平线交点处", position: [-0.02, 0.88, 0.02], indication: "偏头痛、颔颊肿、牙关紧闭、呕吐", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB8", name: "率谷", pinyin: "Shuaigu", meridian: "足少阳胆经", code: "GB", location: "头部，角孙直上入发际1.5寸", position: [-0.02, 0.92, 0.03], indication: "偏头痛、眩晕、呕吐、小儿惊风", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB9", name: "天冲", pinyin: "Tianchong", meridian: "足少阳胆经", code: "GB", location: "头部，耳根后缘直上入发际2寸", position: [-0.03, 0.93, 0.0], indication: "头痛、癫痫、惊恐、齿龈肿痛", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB10", name: "浮白", pinyin: "Fubai", meridian: "足少阳胆经", code: "GB", location: "头部，耳后乳突后上方，天冲与完骨的弧形连线中1/3与上1/3交点处", position: [-0.04, 0.91, -0.02], indication: "头痛、耳鸣、耳聋、齿痛、瘰疬、足痿不行", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB11", name: "头窍阴", pinyin: "Touqiaoyin", meridian: "足少阳胆经", code: "GB", location: "头部，耳后乳突后上方，天冲与完骨的弧形连线中1/3与下1/3交点处", position: [-0.05, 0.89, -0.03], indication: "头痛、眩晕、颈项强痛、胸胁痛、口苦、耳鸣、耳聋", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB12", name: "完骨", pinyin: "Wangu", meridian: "足少阳胆经", code: "GB", location: "头部，耳后乳突后下方凹陷处", position: [-0.06, 0.85, -0.04], indication: "头痛、颈项强痛、颊肿、喉痹、龋齿、口眼歪斜、癫痫、疟疾", method: "斜刺0.5-0.8寸", category: "" },
  { id: "GB13", name: "本神", pinyin: "Benshen", meridian: "足少阳胆经", code: "GB", location: "头部，前发际上0.5寸，神庭旁开3寸", position: [-0.1, 0.92, 0.08], indication: "头痛、目眩、癫痫、小儿惊风、颈项强痛", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB14", name: "阳白", pinyin: "Yangbai", meridian: "足少阳胆经", code: "GB", location: "前额部，瞳孔直上，眉上1寸", position: [-0.04, 0.9, 0.12], indication: "头痛、目眩、目痛、外眦疼痛、眼睑瞤动、雀目", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB15", name: "头临泣", pinyin: "Toulinqi", meridian: "足少阳胆经", code: "GB", location: "头部，阳白直上入发际0.5寸", position: [-0.04, 0.92, 0.1], indication: "头痛、目眩、目赤肿痛、流泪、目翳、鼻塞、癫痫、小儿惊风", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB16", name: "目窗", pinyin: "Muchuang", meridian: "足少阳胆经", code: "GB", location: "头部，头临泣后1寸", position: [-0.04, 0.93, 0.08], indication: "头痛、目眩、目赤肿痛、远视、青盲、面浮肿", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB17", name: "正营", pinyin: "Zhengying", meridian: "足少阳胆经", code: "GB", location: "头部，目窗后1.5寸", position: [-0.04, 0.94, 0.05], indication: "头痛、头晕、目眩、唇吻强急、齿痛", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB18", name: "承灵", pinyin: "Chengling", meridian: "足少阳胆经", code: "GB", location: "头部，正营后1.5寸", position: [-0.04, 0.95, 0.02], indication: "头痛、眩晕、目痛、鼻渊、鼻衄、喘息", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB19", name: "脑空", pinyin: "Naokong", meridian: "足少阳胆经", code: "GB", location: "头部，风池直上，与枕外隆凸相平处", position: [-0.05, 0.92, -0.05], indication: "头痛、颈项强痛、目眩、目赤肿痛、鼻渊、耳聋、癫痫、惊悸", method: "平刺0.5-0.8寸", category: "" },
  { id: "GB20", name: "风池", pinyin: "Fengchi", meridian: "足少阳胆经", code: "GB", location: "项部，枕骨之下，胸锁乳突肌与斜方肌上端之间的凹陷处", position: [-0.06, 0.82, -0.04], indication: "头痛、眩晕、颈项强痛、目赤肿痛、鼻渊、耳鸣、中风、口眼歪斜、热病、感冒、癫痫", method: "针尖微下，向鼻尖方向斜刺0.8-1.2寸", category: "" },
  { id: "GB21", name: "肩井", pinyin: "Jianjing", meridian: "足少阳胆经", code: "GB", location: "肩上，大椎与肩峰端连线的中点", position: [-0.12, 0.7, 0], indication: "头痛、项强、肩背痛、上肢不遂、难产、乳痈、乳汁不下、瘰疬", method: "直刺0.5-0.8寸，不宜深刺", category: "" },
  { id: "GB22", name: "渊腋", pinyin: "Yuanye", meridian: "足少阳胆经", code: "GB", location: "侧胸部，腋中线上，第4肋间隙", position: [-0.18, 0.45, 0], indication: "胸满、胁痛、腋下肿、上肢不举", method: "斜刺或平刺0.5-0.8寸", category: "" },
  { id: "GB23", name: "辄筋", pinyin: "Zhejin", meridian: "足少阳胆经", code: "GB", location: "侧胸部，渊腋前1寸，第4肋间隙", position: [-0.16, 0.45, 0.02], indication: "胸胁痛、呕吐、吞酸、气喘、不嗜食", method: "斜刺或平刺0.5-0.8寸", category: "" },
  { id: "GB24", name: "日月", pinyin: "Riyue", meridian: "足少阳胆经", code: "GB", location: "上腹部，乳头直下，第7肋间隙", position: [-0.1, 0.35, 0.08], indication: "胁肋疼痛、胀满、呕吐、吞酸、呃逆、黄疸", method: "斜刺或平刺0.5-0.8寸", category: "胆募穴" },
  { id: "GB25", name: "京门", pinyin: "Jingmen", meridian: "足少阳胆经", code: "GB", location: "侧腰部，第12肋骨游离端下方", position: [-0.15, 0.2, -0.02], indication: "腹胀、肠鸣、泄泻、腰胁痛", method: "斜刺0.5-0.8寸", category: "肾募穴" },
  { id: "GB26", name: "带脉", pinyin: "Daimai", meridian: "足少阳胆经", code: "GB", location: "侧腹部，第11肋骨游离端直下，与脐相平处", position: [-0.15, 0.1, 0], indication: "月经不调、赤白带下、疝气、腰胁痛", method: "直刺1-1.5寸", category: "带脉交会穴" },
  { id: "GB27", name: "五枢", pinyin: "Wushu", meridian: "足少阳胆经", code: "GB", location: "侧腹部，髂前上棘内侧，带脉下3寸", position: [-0.14, 0, 0.02], indication: "阴挺、赤白带下、疝气、少腹痛、便秘、腰髋痛", method: "直刺1-1.5寸", category: "带脉交会穴" },
  { id: "GB28", name: "维道", pinyin: "Weidao", meridian: "足少阳胆经", code: "GB", location: "侧腹部，髂前上棘前下方，五枢前下0.5寸", position: [-0.13, -0.02, 0.04], indication: "少腹痛、阴挺、疝气、带下、月经不调、腰髋痛", method: "直刺1-1.5寸", category: "带脉交会穴" },
  { id: "GB29", name: "居髎", pinyin: "Juliao", meridian: "足少阳胆经", code: "GB", location: "髋部，髂前上棘与股骨大转子最凸点连线中点处", position: [-0.14, -0.1, 0.04], indication: "腰腿痹痛、瘫痪、足痿", method: "直刺1-1.5寸", category: "" },
  { id: "GB30", name: "环跳", pinyin: "Huantiao", meridian: "足少阳胆经", code: "GB", location: "股外侧部，股骨大转子最凸点与骶管裂孔连线的外1/3与内2/3交点处", position: [-0.14, -0.15, -0.04], indication: "腰腿痹痛、下肢痿痹、半身不遂、挫闪腰痛、风疹", method: "直刺2-3寸", category: "" },
  { id: "GB31", name: "风市", pinyin: "Fengshi", meridian: "足少阳胆经", code: "GB", location: "大腿外侧部，直立，手下垂于体侧，中指尖所指凹陷处", position: [-0.12, -0.3, 0], indication: "中风半身不遂、下肢痿痹、遍身瘙痒、脚气", method: "直刺1-2寸", category: "" },
  { id: "GB32", name: "中渎", pinyin: "Zhongdu", meridian: "足少阳胆经", code: "GB", location: "大腿外侧部，风市下2寸", position: [-0.12, -0.38, 0], indication: "下肢痿痹、半身不遂、麻木", method: "直刺1-2寸", category: "" },
  { id: "GB33", name: "膝阳关", pinyin: "Xiyangguan", meridian: "足少阳胆经", code: "GB", location: "膝外侧，阳陵泉上3寸，股骨外上髁上方凹陷处", position: [-0.1, -0.48, 0.02], indication: "膝膑肿痛、腘筋挛急、小腿麻木", method: "直刺0.8-1寸", category: "" },
  { id: "GB34", name: "阳陵泉", pinyin: "Yanglingquan", meridian: "足少阳胆经", code: "GB", location: "小腿外侧部，腓骨头前下方凹陷处", position: [-0.1, -0.55, 0.03], indication: "半身不遂、下肢痿痹、麻木、膝膑肿痛、脚气、胁肋痛、口苦、呕吐、黄疸、小儿惊风", method: "直刺1-1.5寸", category: "合穴、筋会、胆下合穴" },
  { id: "GB35", name: "阳交", pinyin: "Yangjiao", meridian: "足少阳胆经", code: "GB", location: "小腿外侧部，外踝尖上7寸，腓骨后缘", position: [-0.1, -0.65, 0.02], indication: "胸胁胀满、下肢痿痹、癫狂、面肿、惊恐", method: "直刺0.5-0.8寸", category: "阳维脉郄穴" },
  { id: "GB36", name: "外丘", pinyin: "Waiqiu", meridian: "足少阳胆经", code: "GB", location: "小腿外侧部，外踝尖上7寸，腓骨前缘", position: [-0.1, -0.65, 0.04], indication: "颈项强痛、胸胁痛、下肢痿痹、癫狂、犬伤", method: "直刺0.5-0.8寸", category: "郄穴" },
  { id: "GB37", name: "光明", pinyin: "Guangming", meridian: "足少阳胆经", code: "GB", location: "小腿外侧部，外踝尖上5寸，腓骨前缘", position: [-0.1, -0.7, 0.04], indication: "目痛、夜盲、乳胀痛、下肢痿痹、颊肿", method: "直刺0.5-0.8寸", category: "络穴" },
  { id: "GB38", name: "阳辅", pinyin: "Yangfu", meridian: "足少阳胆经", code: "GB", location: "小腿外侧部，外踝尖上4寸，腓骨前缘稍前方", position: [-0.1, -0.75, 0.05], indication: "偏头痛、目外眦痛、腋下肿痛、瘰疬、胸胁及下肢外侧痛、疟疾、半身不遂", method: "直刺0.5-0.8寸", category: "经穴" },
  { id: "GB39", name: "悬钟", pinyin: "Xuanzhong", meridian: "足少阳胆经", code: "GB", location: "小腿外侧部，外踝尖上3寸，腓骨前缘", position: [-0.1, -0.8, 0.05], indication: "颈项强痛、胸胁胀满、咽喉肿痛、痔疾、下肢痿痹、脚气", method: "直刺0.5-0.8寸", category: "髓会、八会穴" },
  { id: "GB40", name: "丘墟", pinyin: "Qiuxu", meridian: "足少阳胆经", code: "GB", location: "足外侧部，外踝前下方，趾长伸肌腱外侧凹陷处", position: [-0.1, -0.88, 0.06], indication: "颈项痛、腋下肿、胸胁痛、下肢痿痹、外踝肿痛、疟疾、目赤肿痛、目翳", method: "直刺0.5-0.8寸", category: "原穴" },
  { id: "GB41", name: "足临泣", pinyin: "Zulinqi", meridian: "足少阳胆经", code: "GB", location: "足背外侧，第4、5跖骨底部结合部前方凹陷处", position: [-0.1, -0.92, 0.05], indication: "头痛、目眩、目外眦痛、目赤肿痛、乳痈、瘰疬、胁肋痛、疟疾、月经不调、足跗肿痛", method: "直刺0.5-0.8寸", category: "输穴、八脉交会穴" },
  { id: "GB42", name: "地五会", pinyin: "Diwuhui", meridian: "足少阳胆经", code: "GB", location: "足背外侧，第4、5跖骨之间，小趾伸肌腱内侧缘", position: [-0.1, -0.93, 0.04], indication: "头痛、目赤肿痛、耳鸣耳聋、胁肋痛、乳痈、足背肿痛", method: "直刺0.3-0.5寸", category: "" },
  { id: "GB43", name: "侠溪", pinyin: "Xiaxi", meridian: "足少阳胆经", code: "GB", location: "足背外侧，第4、5趾间，趾蹼缘后方赤白肉际处", position: [-0.1, -0.95, 0.03], indication: "头痛、眩晕、耳鸣耳聋、目外眦肿痛、颊肿、胸胁痛、膝股痛、足跗肿痛、热病", method: "直刺0.3-0.5寸", category: "荥穴" },
  { id: "GB44", name: "足窍阴", pinyin: "Zuqiaoyin", meridian: "足少阳胆经", code: "GB", location: "足第4趾末节外侧，趾甲根角旁0.1寸", position: [-0.1, -0.97, 0.02], indication: "头痛、目眩、目赤肿痛、耳聋耳鸣、咽喉肿痛、胸胁痛、热病、多梦", method: "浅刺0.1寸或点刺出血", category: "井穴" },
]
