// 足阳明胃经 (45穴)
import { Acupoint } from './types'

export const STOMACH_MERIDIAN: Acupoint[] = [
  { id: "ST1", name: "承泣", pinyin: "chengqi", code: "ST1", position: [0.10, 2.02, 0.42], meridian: "足阳明胃经", category: "正经", location: "面部，瞳孔直下，眼球与眶下缘之间", effect: "散风清热，明目止泪", method: "直刺或斜刺", depth: "0.3-0.7寸", caution: "不可提插捻转" },
  { id: "ST2", name: "四白", pinyin: "sibai", code: "ST2", position: [0.10, 1.98, 0.42], meridian: "足阳明胃经", category: "正经", location: "面部，瞳孔直下，眶下孔凹陷处", effect: "祛风明目，通络止痛", method: "直刺", depth: "0.3-0.5寸" },
  { id: "ST3", name: "巨髎", pinyin: "juliao", code: "ST3", position: [0.12, 1.95, 0.42], meridian: "足阳明胃经", category: "正经", location: "面部，瞳孔直下，平鼻翼下缘处", effect: "清热熄风，明目退翳", method: "直刺或斜刺", depth: "0.3-0.5寸" },
  { id: "ST4", name: "地仓", pinyin: "dicang", code: "ST4", position: [0.15, 1.90, 0.42], meridian: "足阳明胃经", category: "正经", location: "面部，口角外侧，瞳孔直下", effect: "祛风止痛，舒筋活络", method: "斜刺或平刺", depth: "0.3-0.5寸" },
  { id: "ST5", name: "大迎", pinyin: "daying", code: "ST5", position: [0.18, 1.88, 0.38], meridian: "足阳明胃经", category: "正经", location: "下颌角前方，咬肌附着部前缘", effect: "祛风通络，消肿止痛", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "ST6", name: "颊车", pinyin: "jiache", code: "ST6", position: [0.22, 1.88, 0.32], meridian: "足阳明胃经", category: "正经", location: "面颊部，下颌角前上方约1横指", effect: "祛风清热，开关通络", method: "直刺或斜刺", depth: "0.3-0.5寸" },
  { id: "ST7", name: "下关", pinyin: "xiaguan", code: "ST7", position: [0.25, 1.95, 0.28], meridian: "足阳明胃经", category: "正经", location: "面部耳前方，颧弓与下颌切迹所形成的凹陷中", effect: "消肿止痛，聪耳通络", method: "直刺", depth: "0.3-0.5寸" },
  { id: "ST8", name: "头维", pinyin: "touwei", code: "ST8", position: [0.20, 2.18, 0.20], meridian: "足阳明胃经", category: "正经", location: "头侧部，额角发际上0.5寸", effect: "清头明目，止痛镇痉", method: "平刺", depth: "0.5-1寸" },
  { id: "ST9", name: "人迎", pinyin: "renying", code: "ST9", position: [0.15, 1.80, 0.12], meridian: "足阳明胃经", category: "正经", location: "颈部，喉结旁开1.5寸", effect: "利咽散结，理气降逆", method: "直刺", depth: "0.3-0.5寸", caution: "避开颈动脉" },
  { id: "ST10", name: "水突", pinyin: "shuitu", code: "ST10", position: [0.15, 1.75, 0.12], meridian: "足阳明胃经", category: "正经", location: "颈部，胸锁乳突肌前缘", effect: "清热利咽，降逆平喘", method: "直刺", depth: "0.3-0.5寸" },
  { id: "ST11", name: "气舍", pinyin: "qishe", code: "ST11", position: [0.15, 1.70, 0.12], meridian: "足阳明胃经", category: "正经", location: "颈部，锁骨上窝", effect: "理气化痰，降逆止呕", method: "直刺", depth: "0.3-0.5寸" },
  { id: "ST12", name: "缺盆", pinyin: "quepen", code: "ST12", position: [0.18, 1.65, 0.12], meridian: "足阳明胃经", category: "正经", location: "锁骨上窝中央", effect: "宽胸利膈，止咳平喘", method: "直刺", depth: "0.3-0.5寸", caution: "不可深刺" },
  { id: "ST13", name: "气户", pinyin: "qihu", code: "ST13", position: [0.20, 1.58, 0.15], meridian: "足阳明胃经", category: "正经", location: "胸部，锁骨下缘，前正中线旁开4寸", effect: "理气宽胸，止咳平喘", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "ST14", name: "库房", pinyin: "kufang", code: "ST14", position: [0.20, 1.52, 0.16], meridian: "足阳明胃经", category: "正经", location: "胸部，第1肋间隙，前正中线旁开4寸", effect: "理气宽胸，止咳化痰", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "ST15", name: "屋翳", pinyin: "wuyi", code: "ST15", position: [0.20, 1.46, 0.17], meridian: "足阳明胃经", category: "正经", location: "胸部，第2肋间隙，前正中线旁开4寸", effect: "止咳化痰，消肿止痛", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "ST16", name: "膺窗", pinyin: "yingchuang", code: "ST16", position: [0.20, 1.40, 0.18], meridian: "足阳明胃经", category: "正经", location: "胸部，第3肋间隙，前正中线旁开4寸", effect: "宽胸理气，消肿止痛", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "ST17", name: "乳中", pinyin: "ruzhong", code: "ST17", position: [0.20, 1.34, 0.19], meridian: "足阳明胃经", category: "正经", location: "胸部，乳头中央", effect: "定位取穴标志", method: "禁针灸", caution: "禁针灸" },
  { id: "ST18", name: "乳根", pinyin: "rugen", code: "ST18", position: [0.20, 1.28, 0.19], meridian: "足阳明胃经", category: "正经", location: "胸部，乳头直下，第5肋间隙", effect: "通乳化瘀，宽胸利气", method: "斜刺", depth: "0.3-0.5寸" },
  { id: "ST19", name: "不容", pinyin: "burong", code: "ST19", position: [0.10, 1.18, 0.18], meridian: "足阳明胃经", category: "正经", location: "上腹部，脐中上6寸，前正中线旁开2寸", effect: "调中和胃，理气止痛", method: "直刺", depth: "0.5-0.8寸" },
  { id: "ST20", name: "承满", pinyin: "chengman", code: "ST20", position: [0.10, 1.14, 0.18], meridian: "足阳明胃经", category: "正经", location: "上腹部，脐中上5寸，前正中线旁开2寸", effect: "理气和胃，降逆止呕", method: "直刺", depth: "0.5-0.8寸" },
  { id: "ST21", name: "梁门", pinyin: "liangmen", code: "ST21", position: [0.10, 1.10, 0.18], meridian: "足阳明胃经", category: "正经", location: "上腹部，脐中上4寸，前正中线旁开2寸", effect: "和胃理气，健脾消食", method: "直刺", depth: "0.5-1寸" },
  { id: "ST22", name: "关门", pinyin: "guanmen", code: "ST22", position: [0.10, 1.06, 0.18], meridian: "足阳明胃经", category: "正经", location: "上腹部，脐中上3寸，前正中线旁开2寸", effect: "调理肠胃，利水消肿", method: "直刺", depth: "0.5-1寸" },
  { id: "ST23", name: "太乙", pinyin: "taiyi", code: "ST23", position: [0.10, 1.02, 0.18], meridian: "足阳明胃经", category: "正经", location: "上腹部，脐中上2寸，前正中线旁开2寸", effect: "安神定志，健脾和胃", method: "直刺", depth: "0.5-1寸" },
  { id: "ST24", name: "滑肉门", pinyin: "huaroumen", code: "ST24", position: [0.10, 0.98, 0.17], meridian: "足阳明胃经", category: "正经", location: "上腹部，脐中上1寸，前正中线旁开2寸", effect: "镇惊安神，调理肠胃", method: "直刺", depth: "0.5-1寸" },
  { id: "ST25", name: "天枢", pinyin: "tianshu", code: "ST25", position: [0.10, 0.92, 0.16], meridian: "足阳明胃经", category: "正经", location: "腹中部，脐中旁开2寸", effect: "调中和胃，理气健脾", method: "直刺", depth: "1-1.5寸" },
  { id: "ST26", name: "外陵", pinyin: "wailing", code: "ST26", position: [0.10, 0.88, 0.16], meridian: "足阳明胃经", category: "正经", location: "下腹部，脐中下1寸，前正中线旁开2寸", effect: "理气止痛，调经止带", method: "直刺", depth: "0.5-1寸" },
  { id: "ST27", name: "大巨", pinyin: "daju", code: "ST27", position: [0.10, 0.84, 0.15], meridian: "足阳明胃经", category: "正经", location: "下腹部，脐中下2寸，前正中线旁开2寸", effect: "调经止带，调理下焦", method: "直刺", depth: "0.5-1.5寸" },
  { id: "ST28", name: "水道", pinyin: "shuidao", code: "ST28", position: [0.10, 0.80, 0.15], meridian: "足阳明胃经", category: "正经", location: "下腹部，脐中下3寸，前正中线旁开2寸", effect: "利水消肿，调经止痛", method: "直刺", depth: "0.5-1.5寸" },
  { id: "ST29", name: "归来", pinyin: "guilai", code: "ST29", position: [0.10, 0.76, 0.15], meridian: "足阳明胃经", category: "正经", location: "下腹部，脐中下4寸，前正中线旁开2寸", effect: "活血调经，升举下陷", method: "直刺", depth: "0.5-1.5寸" },
  { id: "ST30", name: "气冲", pinyin: "qichong", code: "ST30", position: [0.10, 0.70, 0.14], meridian: "足阳明胃经", category: "正经", location: "腹股沟区，耻骨联合上缘，前正中线旁开2寸", effect: "理气止痛，调经止带", method: "直刺", depth: "0.5-1寸", caution: "避开股动脉" },
  { id: "ST31", name: "髀关", pinyin: "biguan", code: "ST31", position: [0.18, 0.55, 0.10], meridian: "足阳明胃经", category: "正经", location: "大腿前面，髂前上棘与髌底外侧端连线上", effect: "强腰膝，通经络", method: "直刺", depth: "1-2寸" },
  { id: "ST32", name: "伏兔", pinyin: "futu", code: "ST32", position: [0.18, 0.42, 0.11], meridian: "足阳明胃经", category: "正经", location: "大腿前面，髌底上6寸", effect: "散寒化湿，通经活络", method: "直刺", depth: "1-2寸" },
  { id: "ST33", name: "阴市", pinyin: "yinshi", code: "ST33", position: [0.18, 0.32, 0.11], meridian: "足阳明胃经", category: "正经", location: "大腿前面，髌底上3寸", effect: "温经散寒，理气止痛", method: "直刺", depth: "1-1.5寸" },
  { id: "ST34", name: "梁丘", pinyin: "liangqiu", code: "ST34", position: [0.18, 0.25, 0.11], meridian: "足阳明胃经", category: "正经", location: "大腿前面，髌底上2寸", effect: "和胃理气，通经活络", method: "直刺", depth: "0.5-1.2寸" },
  { id: "ST35", name: "犊鼻", pinyin: "dubi", code: "ST35", position: [0.19, 0.15, 0.12], meridian: "足阳明胃经", category: "正经", location: "膝部，髌韧带外侧凹陷中", effect: "通经活络，疏风散寒", method: "斜刺", depth: "0.5-1寸" },
  { id: "ST36", name: "足三里", pinyin: "zusanli", code: "ST36", position: [0.20, 0.05, 0.12], meridian: "足阳明胃经", category: "正经", location: "小腿前外侧，犊鼻下3寸，距胫骨前缘1横指", effect: "健脾和胃，扶正培元，通经活络", method: "直刺", depth: "1-2寸" },
  { id: "ST37", name: "上巨虚", pinyin: "shangjuxu", code: "ST37", position: [0.20, -0.05, 0.12], meridian: "足阳明胃经", category: "正经", location: "小腿前外侧，犊鼻下6寸", effect: "调肠胃，通经络", method: "直刺", depth: "1-2寸" },
  { id: "ST38", name: "条口", pinyin: "tiaokou", code: "ST38", position: [0.20, -0.12, 0.12], meridian: "足阳明胃经", category: "正经", location: "小腿前外侧，犊鼻下8寸", effect: "舒筋活络，理气和中", method: "直刺", depth: "1-1.5寸" },
  { id: "ST39", name: "下巨虚", pinyin: "xiajuxu", code: "ST39", position: [0.20, -0.18, 0.12], meridian: "足阳明胃经", category: "正经", location: "小腿前外侧，犊鼻下9寸", effect: "调肠腑，通经络", method: "直刺", depth: "1-1.5寸" },
  { id: "ST40", name: "丰隆", pinyin: "fenglong", code: "ST40", position: [0.22, -0.12, 0.10], meridian: "足阳明胃经", category: "正经", location: "小腿前外侧，条口穴外侧1寸", effect: "和胃化痰，通络安神", method: "直刺", depth: "1-1.5寸" },
  { id: "ST41", name: "解溪", pinyin: "jiexi", code: "ST41", position: [0.18, -0.45, 0.12], meridian: "足阳明胃经", category: "正经", location: "足背与小腿交界处横纹中央凹陷中", effect: "清胃化痰，镇惊安神", method: "直刺", depth: "0.3-0.5寸" },
  { id: "ST42", name: "冲阳", pinyin: "chongyang", code: "ST42", position: [0.16, -0.52, 0.15], meridian: "足阳明胃经", category: "正经", location: "足背最高处，第2、3跖骨结合部前方凹陷中", effect: "和胃化痰，通络宁神", method: "直刺", depth: "0.3-0.5寸", caution: "避开足背动脉" },
  { id: "ST43", name: "陷谷", pinyin: "xiangu", code: "ST43", position: [0.15, -0.58, 0.15], meridian: "足阳明胃经", category: "正经", location: "足背，第2、3跖骨结合部前方凹陷中", effect: "和胃行水，理气止痛", method: "直刺", depth: "0.3-0.5寸" },
  { id: "ST44", name: "内庭", pinyin: "neiting", code: "ST44", position: [0.14, -0.64, 0.15], meridian: "足阳明胃经", category: "正经", location: "足背，第2、3趾间缝纹端", effect: "清胃泻火，通络止痛", method: "直刺或斜刺", depth: "0.3-0.5寸" },
  { id: "ST45", name: "厉兑", pinyin: "lidui", code: "ST45", position: [0.13, -0.68, 0.15], meridian: "足阳明胃经", category: "正经", location: "足第2趾末节外侧，距趾甲角0.1寸", effect: "清热和胃，苏厥醒神", method: "浅刺", depth: "0.1寸或点刺出血" },
]
